In [3]:
import requests
import time
import json
import re
import random
from tqdm import tqdm
from google.colab import files

HEADERS = {
    "User-Agent": "MyColabBot/2.0 (inesgoddi@gmail.com)"
}

SESSION = requests.Session()
SESSION.headers.update(HEADERS)

API_SIMPLE = "https://simple.wikipedia.org/w/api.php"
API_EN = "https://en.wikipedia.org/w/api.php"

REQUEST_DELAY = 1.0
MAX_RETRIES = 8

DISCIPLINARY_ROOTS = [
    # Natural sciences
    "Physics", "Chemistry", "Biology", "Astronomy", "Earth science",

    # Formal sciences
    "Mathematics", "Computer science", "Statistics", "Logic",

    # Life sciences
    "Genetics", "Neuroscience", "Ecology", "Microbiology",
    "Zoology", "Botany",

    # Medical sciences
    "Medicine", "Surgery", "Pharmacology", "Epidemiology", "Public health",

    # Engineering
    "Engineering", "Mechanical engineering", "Electrical engineering",
    "Civil engineering", "Chemical engineering", "Aerospace engineering",

    # Social sciences
    "Economics", "Psychology", "Sociology", "Political science",
    "Anthropology", "Human geography",

    # Humanities
    "Philosophy", "History", "Literature", "Linguistics", "Theology",

    # Arts
    "Arts", "Music", "Visual arts", "Performing arts",
    "Film studies", "Architecture",

    # Interdisciplinary
    "Cognitive science", "Environmental science",
    "Data science", "Artificial intelligence", "Systems science"
]

BAD_CATEGORY_PATTERNS = [
    r"^Articles? ", r"^All articles?", r"^Wikipedia ", r"^Pages?",
    r"^CS1 ", r"^Harv ", r"^Use ", r"^Redirects?",
    r"^Disambiguation", r".*errors?$", r".*cleanup.*",
    r".*needing.*", r".*lacking.*", r".*unsourced.*",
    r".*unreferenced.*", r".*broken.*", r".*template.*",
    r".*infobox.*", r".*Wikidata.*", r".*stub.*",
    r".*stubs.*", r".*citation.*", r".*coordinates.*",
    r".*authority control.*", r".*public domain.*",
    r".*incorporating.*", r".*semi-protected.*",
    r".*plot summary.*", r".*bare URLs.*",
    r".*subscription.*", r".*maintenance.*",
    r".*hidden categor.*"
]

BAD_EXACT_CATEGORIES = {
    "Contents", "Lists", "Outlines", "Reference",
    "Comparisons", "Concepts", "Entities",
    "Objects", "Data", "Information"
}

BAD_CATEGORY_REGEX = [re.compile(p, re.IGNORECASE) for p in BAD_CATEGORY_PATTERNS]

DIGIT_PATTERN = re.compile(r"\d")
NON_ALPHA_PATTERN = re.compile(r"[^a-zA-Z\- ]")

BAD_WORDS = {
    "abuse", "abusive", "violence", "violent", "rape", "murder",
    "death", "torture", "prostitution", "porn",
    "sexual", "sex", "cannibal", "cannibalism", "drug",
    "addiction", "gambling", "terrorism", "crime", "criminal",
    "childhood", "children"
}

PEOPLE_PATTERN = re.compile(
    r"\b(bankers?|lawyers?|politicians?|actors?|singers?|players?|"
    r"scientists?|philosophers?|historians?|mathematicians?|"
    r"writers?|authors?|artists?|athletes?|accountants?)\b",
    re.IGNORECASE
)

IST_PATTERN = re.compile(r"\b\w+ist(s)?\b", re.IGNORECASE)
NAME_PATTERN = re.compile(r"^[A-Z][a-z]+ [A-Z][a-z]+$")


def is_disciplinary_category(cat):
    cat = cat.strip()
    cat_lower = cat.lower()

    if cat in BAD_EXACT_CATEGORIES:
        return False

    if any(p.search(cat) for p in BAD_CATEGORY_REGEX):
        return False

    if DIGIT_PATTERN.search(cat):
        return False

    if NON_ALPHA_PATTERN.search(cat):
        return False

    if any(word in cat_lower for word in BAD_WORDS):
        return False

    if PEOPLE_PATTERN.search(cat):
        return False

    if IST_PATTERN.search(cat):
        return False

    if NAME_PATTERN.match(cat):
        return False

    if len(cat.split()) > 1:
        return False
    # strict single-word (letters only, no spaces, no hyphens)
    if not re.fullmatch(r"[A-Za-z]+", cat):
      return False

    return True


def safe_get(api_url, params, max_retries=MAX_RETRIES):
    for attempt in range(max_retries):
        try:
            response = SESSION.get(api_url, params=params, timeout=30)

            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After")

                if retry_after:
                    wait = int(retry_after)
                else:
                    wait = min(90, 5 * (2 ** attempt))

                wait += random.uniform(0, 2)
                print(f"429 rate limit. Waiting {wait:.1f}s...")
                time.sleep(wait)
                continue

            response.raise_for_status()

            time.sleep(REQUEST_DELAY + random.uniform(0, 0.5))
            return response.json()

        except requests.exceptions.RequestException as e:
            wait = min(90, 3 * (2 ** attempt)) + random.uniform(0, 2)
            print(f"Request failed: {e}. Waiting {wait:.1f}s...")
            time.sleep(wait)

    return {}


def get_subcategories(category, api_url, depth=5):
    seen = set()
    to_visit = [(category, 0)]
    results = set()

    while to_visit:
        current_cat, current_depth = to_visit.pop()

        if current_cat in seen or current_depth > depth:
            continue

        seen.add(current_cat)
        cmcontinue = None

        while True:
            params = {
                "action": "query",
                "format": "json",
                "list": "categorymembers",
                "cmtitle": f"Category:{current_cat}",
                "cmnamespace": 14,
                "cmlimit": 500
            }

            if cmcontinue:
                params["cmcontinue"] = cmcontinue

            data = safe_get(api_url, params)

            subcats = [
                item["title"].replace("Category:", "")
                for item in data.get("query", {}).get("categorymembers", [])
            ]

            for subcat in subcats:
                if is_disciplinary_category(subcat):
                    results.add(subcat)

                    if current_depth < depth:
                        to_visit.append((subcat, current_depth + 1))

            cmcontinue = data.get("continue", {}).get("cmcontinue")

            if not cmcontinue:
                break

    return results


def fetch_root_subcats(cat):
    print(f"\nProcessing root category: {cat}")

    simple = get_subcategories(cat, API_SIMPLE, depth=7)
    en = get_subcategories(cat, API_EN, depth=7)

    return simple, en


print("Using predefined disciplinary root categories...")

subcategories_simple = set()
subcategories_en = set()

for cat in tqdm(DISCIPLINARY_ROOTS, desc="Getting subcategories"):
    simple, en = fetch_root_subcats(cat)
    subcategories_simple.update(simple)
    subcategories_en.update(en)

common_cats = sorted(
    (subcategories_simple & subcategories_en) | set(DISCIPLINARY_ROOTS)
)

common_cats = [
    cat for cat in common_cats
    if is_disciplinary_category(cat)
]

print(f"\nKept {len(common_cats)} disciplinary categories.")

with open("disciplinary_categories3.json", "w", encoding="utf-8") as f:
    json.dump(common_cats, f, ensure_ascii=False, indent=2)

files.download("disciplinary_categories3.json")

Using predefined disciplinary root categories...

Getting subcategories:   0%|          | 0/48 [00:00<?, ?it/s]

Processing root category: Physics

Getting subcategories:   2%|▏         | 1/48 [02:18<1:48:15, 138.21s/it]

Processing root category: Chemistry

Getting subcategories:   4%|▍         | 2/48 [02:57<1:01:09, 79.77s/it]

Processing root category: Biology

Getting subcategories:   6%|▋         | 3/48 [15:05<4:41:59, 375.99s/it]

Processing root category: Astronomy

Getting subcategories:   8%|▊         | 4/48 [16:22<3:09:02, 257.78s/it]

Processing root category: Earth science

Getting subcategories:  10%|█         | 5/48 [16:24<1:58:49, 165.79s/it]

Processing root category: Mathematics

Getting subcategories:  12%|█▎        | 6/48 [17:00<1:25:03, 121.50s/it]

Processing root category: Computer science

Getting subcategories:  15%|█▍        | 7/48 [17:39<1:04:31, 94.42s/it]

Processing root category: Statistics

Getting subcategories:  17%|█▋        | 8/48 [17:46<44:27, 66.68s/it]

Processing root category: Logic

Getting subcategories:  19%|█▉        | 9/48 [18:09<34:31, 53.12s/it]

Processing root category: Genetics

Getting subcategories:  21%|██        | 10/48 [19:04<33:58, 53.63s/it]

Processing root category: Neuroscience

Getting subcategories:  23%|██▎       | 11/48 [25:21<1:34:05, 152.58s/it]

Processing root category: Ecology

Getting subcategories:  25%|██▌       | 12/48 [27:14<1:24:21, 140.60s/it]

Processing root category: Microbiology

Getting subcategories:  27%|██▋       | 13/48 [29:38<1:22:40, 141.73s/it]

Processing root category: Zoology

Getting subcategories:  29%|██▉       | 14/48 [43:36<3:19:27, 351.98s/it]

Processing root category: Botany

Getting subcategories:  31%|███▏      | 15/48 [46:09<2:40:35, 291.99s/it]

Processing root category: Medicine

Getting subcategories:  33%|███▎      | 16/48 [46:26<1:51:29, 209.03s/it]

Processing root category: Surgery

Getting subcategories:  35%|███▌      | 17/48 [46:54<1:19:57, 154.77s/it]

Processing root category: Pharmacology

Getting subcategories:  38%|███▊      | 18/48 [47:19<57:50, 115.70s/it]

Processing root category: Epidemiology

Getting subcategories:  40%|███▉      | 19/48 [47:25<39:59, 82.75s/it]

Processing root category: Public health

Getting subcategories:  42%|████▏     | 20/48 [52:53<1:12:57, 156.34s/it]

Processing root category: Engineering

Getting subcategories:  44%|████▍     | 21/48 [53:00<50:17, 111.76s/it]

Processing root category: Mechanical engineering

Getting subcategories:  46%|████▌     | 22/48 [1:00:04<1:28:58, 205.31s/it]

Processing root category: Electrical engineering

Getting subcategories:  48%|████▊     | 23/48 [1:00:07<1:00:18, 144.75s/it]

Processing root category: Civil engineering

Getting subcategories:  50%|█████     | 24/48 [1:02:53<1:00:24, 151.02s/it]

Processing root category: Chemical engineering

Getting subcategories:  52%|█████▏    | 25/48 [1:02:59<41:13, 107.55s/it]

Processing root category: Aerospace engineering

Getting subcategories:  54%|█████▍    | 26/48 [1:03:38<31:49, 86.81s/it]

Processing root category: Economics

Getting subcategories:  56%|█████▋    | 27/48 [1:06:35<39:51, 113.88s/it]

Processing root category: Psychology

Getting subcategories:  58%|█████▊    | 28/48 [1:11:04<53:31, 160.55s/it]

Processing root category: Sociology

Getting subcategories:  60%|██████    | 29/48 [1:12:08<41:38, 131.48s/it]

Processing root category: Political science

Getting subcategories:  62%|██████▎   | 30/48 [1:12:17<28:25, 94.76s/it]

Processing root category: Anthropology

Getting subcategories:  65%|██████▍   | 31/48 [1:13:58<27:24, 96.71s/it]

Processing root category: Human geography

Getting subcategories:  67%|██████▋   | 32/48 [1:14:44<21:43, 81.45s/it]

Processing root category: Philosophy

Getting subcategories:  69%|██████▉   | 33/48 [1:15:05<15:49, 63.32s/it]

Processing root category: History

Getting subcategories:  71%|███████   | 34/48 [1:20:06<31:26, 134.73s/it]

Processing root category: Literature

Getting subcategories:  73%|███████▎  | 35/48 [1:20:46<22:59, 106.14s/it]

Processing root category: Linguistics

Getting subcategories:  75%|███████▌  | 36/48 [1:23:07<23:18, 116.56s/it]

Processing root category: Theology

Getting subcategories:  77%|███████▋  | 37/48 [1:25:12<21:52, 119.31s/it]

Processing root category: Arts

Getting subcategories:  79%|███████▉  | 38/48 [1:25:16<14:04, 84.44s/it]

Processing root category: Music

Getting subcategories:  81%|████████▏ | 39/48 [1:25:24<09:15, 61.71s/it]

Processing root category: Visual arts

Getting subcategories:  83%|████████▎ | 40/48 [1:27:44<11:20, 85.09s/it]

Processing root category: Performing arts

Getting subcategories:  85%|████████▌ | 41/48 [1:42:35<38:07, 326.81s/it]

Processing root category: Film studies

Getting subcategories:  88%|████████▊ | 42/48 [1:42:38<22:58, 229.71s/it]

Processing root category: Architecture

Getting subcategories:  90%|████████▉ | 43/48 [1:44:32<16:14, 194.96s/it]

Processing root category: Cognitive science

Getting subcategories:  92%|█████████▏| 44/48 [1:55:20<22:03, 330.84s/it]

Processing root category: Environmental science

Getting subcategories:  94%|█████████▍| 45/48 [1:56:54<12:59, 259.84s/it]

Processing root category: Data science

Getting subcategories:  96%|█████████▌| 46/48 [1:56:57<06:05, 182.87s/it]

Processing root category: Artificial intelligence

Getting subcategories:  98%|█████████▊| 47/48 [1:57:02<02:09, 129.40s/it]

Processing root category: Systems science

Getting subcategories: 100%|██████████| 48/48 [1:57:14<00:00, 146.55s/it]

Kept 242 disciplinary categories.

In [ ]:
import json

with open("disciplinary_categories3.json", "r") as file:
    common_cats= json.load(file)

print(len(common_cats))

267

In [5]:

n = [
    "Anniversaries",
    "Architects",
    "Astronauts",
    "Astronomers",
    "Beekeepers",
    "Birthdays",
    "Choreographers",
    "Dancers",
    "Engineers",
    "Firefighters",
    "Islamophobia",
    "Plumbers",
    "Statisticians",
    "Surgeons",
    "Woodworkers",
    "Zoos"
]


result = [x for x in common_cats if x not in n]

print(len(result))

227

In [8]:
for i in result :
  print(i)

Acceleration
Adhesives
Algae
Amphibians
Angels
Animals
Annelids
Anthropology
Antisemitism
Aquariums
Archaeology
Architecture
Archives
Archosaurs
Arthropods
Arts
Astronomy
Autism
Bacteria
Beekeeping
Biology
Biomes
Birds
Birth
Books
Botany
Botnets
Brachiopods
Caecilians
Calendars
Carpenters
Cats
Centuries
Charts
Chemistry
Chromosomes
Chronology
Clocks
Cloning
Cockatoos
Cognition
Colors
Comics
Constellations
Construction
Costumes
Creativity
Cryptozoology
Dance
Dances
Days
Decades
Demolition
Demons
Deserts
Diagrams
Diapsids
Disasters
Documents
Dogs
Drama
Echinoderms
Ecology
Economics
Ecoregions
Ecosystems
Emotions
Engineering
Entomology
Epidemiology
Establishments
Ethnocentrism
Ethology
Eukaryotes
Extinction
Extremophiles
Fertilizers
Fire
Firefighting
Fires
Flags
Flatworms
Forestry
Forests
Frogs
Fungi
Gardening
Gardens
Gemstones
Genetics
Giftedness
Glaciers
Glass
Goods
Graphics
Grasslands
Happiness
Herbicides
Hippopotamuses
Historiography
History
Hydropower
Illusions
Infrastructure
Innovation
Insecticides
Insects
Intelligence
Invertebrates
Journalism
Kinematics
Learning
Light
Lighthouses
Lighting
Linguistics
Literature
Logic
Love
Machines
Mammals
Manga
Manufacturing
Manuscripts
Mascots
Materials
Mathematics
Mechanics
Medicine
Mesonychids
Metalworking
Microbiology
Migraine
Millennia
Modernism
Modernity
Molluscs
Months
Mosaics
Museums
Music
Narcissism
Nematodes
Neuropsychology
Neuroscience
Newts
Nucleotides
Observances
Observation
Opera
Operas
Optoelectronics
Organisms
Oscillation
Pain
Paints
Pamphlets
Parades
Parasites
Parrots
Pendulums
Perception
Pesticides
Pharmacology
Phenomena
Philosophy
Phobias
Photovoltaics
Physics
Plays
Poisons
Pottery
Profanity
Prokaryotes
Psychology
Publications
Punctuation
Rainforests
Rationalism
Reasoning
Reptiles
Rhetoric
Robots
Salamanders
Salamandridae
Satellites
Scorpius
Seasons
Semiconductors
Smartwatches
Snow
Sociology
Software
Spacecraft
Spaceflight
Sponges
Statistics
Submarines
Surgery
Surrealism
Symbols
Television
Tetrapods
Theatre
Theatres
Theism
Theology
Toads
Tourism
Training
Treaties
Tropes
Turtles
Ungulates
Vaccines
Vehicles
Vultures
Watches
Water
Waves
Wetlands
Wolves
Woodworking
Xenacoelomorpha
Xenophobia
Years
Zoology

In [12]:
from numpy import char
import requests
import time
import json
import random
import csv
import re
from tqdm import tqdm
import pandas as pd
from google.colab import files

HEADERS = {
    "User-Agent": "MyColabBot/1.0 (inesgoddi@gmail.com)"
}

API_SIMPLE = "https://simple.wikipedia.org/w/api.php"
API_EN = "https://en.wikipedia.org/w/api.php"

# =========================
# 2. COLLECT ARTICLE TITLES
# =========================

matched_pairs = []

MAX_TOTAL_PAIRS = 10000
MAX_ARTICLES_PER_CATEGORY = 500

for cat in tqdm(result, desc="Collecting articles"):
    if len(cat.split()) >1 or any(char.isdigit() for char in cat):
        continue

    print(f"Collecting articles for category: {cat}")
    titles_simple = get_category_articles(
        cat,
        API_SIMPLE,
        limit=MAX_ARTICLES_PER_CATEGORY
    )

    if not titles_simple:
        continue

    existing_in_en = filter_existing_titles_in_en(titles_simple)

    count_for_cat = 0

    for title in existing_in_en:
        matched_pairs.append({
            "category": cat,
            "title": title
        })

        count_for_cat += 1

        if count_for_cat >= MAX_ARTICLES_PER_CATEGORY:
            break

        if len(matched_pairs) >= MAX_TOTAL_PAIRS:
            break

    if len(matched_pairs) >= MAX_TOTAL_PAIRS:
        break

with open("category_title_pairs_disciplinary3.json", "w", encoding="utf-8") as f:
    json.dump(matched_pairs, f, ensure_ascii=False, indent=2)

print(f"Collected {len(matched_pairs)} category-title pairs.")
print(matched_pairs)

Collecting articles:   0%|          | 0/227 [00:00<?, ?it/s]

Collecting articles for category: Acceleration

Collecting articles:   0%|          | 1/227 [00:02<10:45,  2.86s/it]

Collecting articles for category: Adhesives

Collecting articles:   1%|          | 2/227 [00:05<10:53,  2.91s/it]

Collecting articles for category: Algae

Collecting articles:   1%|▏         | 3/227 [00:08<11:07,  2.98s/it]

Collecting articles for category: Amphibians

Collecting articles:   2%|▏         | 4/227 [00:12<11:19,  3.05s/it]

Collecting articles for category: Angels

Collecting articles:   2%|▏         | 5/227 [00:15<11:28,  3.10s/it]

Collecting articles for category: Animals

Collecting articles:   3%|▎         | 6/227 [00:18<11:33,  3.14s/it]

Collecting articles for category: Annelids

Collecting articles:   3%|▎         | 7/227 [00:21<11:19,  3.09s/it]

Collecting articles for category: Anthropology

Collecting articles:   4%|▎         | 8/227 [00:26<13:18,  3.64s/it]

Collecting articles for category: Antisemitism

Collecting articles:   4%|▍         | 9/227 [00:31<14:41,  4.04s/it]

Collecting articles for category: Aquariums

Collecting articles:   4%|▍         | 10/227 [00:34<13:43,  3.79s/it]

Collecting articles for category: Archaeology

Collecting articles:   5%|▍         | 11/227 [00:37<12:43,  3.54s/it]

Collecting articles for category: Architecture

Collecting articles:   5%|▌         | 12/227 [00:40<12:33,  3.50s/it]

Collecting articles for category: Archives

Collecting articles:   6%|▌         | 13/227 [00:43<11:54,  3.34s/it]

Collecting articles for category: Archosaurs

Collecting articles:   6%|▌         | 14/227 [00:47<11:51,  3.34s/it]

Collecting articles for category: Arthropods

Collecting articles:   7%|▋         | 15/227 [00:50<11:40,  3.30s/it]

Collecting articles for category: Arts

Collecting articles:   7%|▋         | 16/227 [00:51<09:35,  2.73s/it]

Collecting articles for category: Astronomy

Collecting articles:   7%|▋         | 17/227 [00:55<11:03,  3.16s/it]

Collecting articles for category: Autism

Collecting articles:   8%|▊         | 18/227 [00:59<10:59,  3.16s/it]

Collecting articles for category: Bacteria

Collecting articles:   8%|▊         | 19/227 [01:02<10:50,  3.13s/it]

Collecting articles for category: Beekeeping

Collecting articles:   9%|▉         | 20/227 [01:05<10:46,  3.12s/it]

Collecting articles for category: Biology

Collecting articles:   9%|▉         | 21/227 [01:10<12:32,  3.65s/it]

Collecting articles for category: Biomes

Collecting articles:  10%|▉         | 22/227 [01:13<11:51,  3.47s/it]

Collecting articles for category: Birds

Collecting articles:  10%|█         | 23/227 [01:18<13:20,  3.93s/it]

Collecting articles for category: Birth

Collecting articles:  11%|█         | 24/227 [01:21<12:36,  3.73s/it]

Collecting articles for category: Books

Collecting articles:  11%|█         | 25/227 [01:24<11:59,  3.56s/it]

Collecting articles for category: Botany

Collecting articles:  11%|█▏        | 26/227 [01:27<11:30,  3.44s/it]

Collecting articles for category: Botnets

Collecting articles:  12%|█▏        | 27/227 [01:30<11:17,  3.39s/it]

Collecting articles for category: Brachiopods

Collecting articles:  12%|█▏        | 28/227 [01:34<11:07,  3.36s/it]

Collecting articles for category: Caecilians

Collecting articles:  13%|█▎        | 29/227 [01:37<10:50,  3.28s/it]

Collecting articles for category: Calendars

Collecting articles:  13%|█▎        | 30/227 [01:41<11:55,  3.63s/it]

Collecting articles for category: Carpenters

Collecting articles:  14%|█▎        | 31/227 [01:45<11:48,  3.62s/it]

Collecting articles for category: Cats

Collecting articles:  14%|█▍        | 32/227 [01:48<11:09,  3.43s/it]

Collecting articles for category: Centuries

Collecting articles:  15%|█▍        | 33/227 [01:51<10:32,  3.26s/it]

Collecting articles for category: Charts

Collecting articles:  15%|█▍        | 34/227 [01:54<10:32,  3.28s/it]

Collecting articles for category: Chemistry

Collecting articles:  15%|█▌        | 35/227 [02:00<13:26,  4.20s/it]

Collecting articles for category: Chromosomes

Collecting articles:  16%|█▌        | 36/227 [02:04<12:31,  3.93s/it]

Collecting articles for category: Chronology

Collecting articles:  16%|█▋        | 37/227 [02:07<11:47,  3.73s/it]

Collecting articles for category: Clocks

Collecting articles:  17%|█▋        | 38/227 [02:10<11:21,  3.61s/it]

Collecting articles for category: Cloning

Collecting articles:  17%|█▋        | 39/227 [02:13<10:44,  3.43s/it]

Collecting articles for category: Cockatoos

Collecting articles:  18%|█▊        | 40/227 [02:16<10:22,  3.33s/it]

Collecting articles for category: Cognition

Collecting articles:  18%|█▊        | 41/227 [02:20<10:21,  3.34s/it]

Collecting articles for category: Colors

Collecting articles:  19%|█▊        | 42/227 [02:23<10:08,  3.29s/it]

Collecting articles for category: Comics

Collecting articles:  19%|█▉        | 43/227 [02:26<10:04,  3.28s/it]

Collecting articles for category: Constellations

Collecting articles:  19%|█▉        | 44/227 [02:31<11:37,  3.81s/it]

Collecting articles for category: Construction

Collecting articles:  20%|█▉        | 45/227 [02:35<11:05,  3.66s/it]

Collecting articles for category: Costumes

Collecting articles:  20%|██        | 46/227 [02:38<10:49,  3.59s/it]

Collecting articles for category: Creativity

Collecting articles:  21%|██        | 47/227 [02:41<10:40,  3.56s/it]

Collecting articles for category: Cryptozoology

Collecting articles:  21%|██        | 48/227 [02:45<10:12,  3.42s/it]

Collecting articles for category: Dance

Collecting articles:  22%|██▏       | 49/227 [02:48<10:08,  3.42s/it]

Collecting articles for category: Dances

Collecting articles:  22%|██▏       | 50/227 [02:51<09:56,  3.37s/it]

Collecting articles for category: Days

Collecting articles:  22%|██▏       | 51/227 [02:54<09:44,  3.32s/it]

Collecting articles for category: Decades

Collecting articles:  23%|██▎       | 52/227 [02:57<09:13,  3.16s/it]

Collecting articles for category: Demolition

Collecting articles:  23%|██▎       | 53/227 [03:00<08:49,  3.04s/it]

Collecting articles for category: Demons

Collecting articles:  24%|██▍       | 54/227 [03:03<08:41,  3.01s/it]

Collecting articles for category: Deserts

Collecting articles:  24%|██▍       | 55/227 [03:06<08:24,  2.93s/it]

Collecting articles for category: Diagrams

Collecting articles:  25%|██▍       | 56/227 [03:09<08:34,  3.01s/it]

Collecting articles for category: Diapsids

Collecting articles:  25%|██▌       | 57/227 [03:12<08:40,  3.06s/it]

Collecting articles for category: Disasters

Collecting articles:  26%|██▌       | 58/227 [03:15<08:42,  3.09s/it]

Collecting articles for category: Documents

Collecting articles:  26%|██▌       | 59/227 [03:18<08:39,  3.09s/it]

Collecting articles for category: Dogs

Collecting articles:  26%|██▋       | 60/227 [03:22<08:41,  3.13s/it]

Collecting articles for category: Drama

Collecting articles:  27%|██▋       | 61/227 [03:24<08:30,  3.08s/it]

Collecting articles for category: Echinoderms

Collecting articles:  27%|██▋       | 62/227 [03:28<08:32,  3.11s/it]

Collecting articles for category: Ecology

Collecting articles:  28%|██▊       | 63/227 [03:32<09:43,  3.56s/it]

Collecting articles for category: Economics

Collecting articles:  28%|██▊       | 64/227 [03:39<12:00,  4.42s/it]

Collecting articles for category: Ecoregions

Collecting articles:  29%|██▊       | 65/227 [03:42<10:40,  3.95s/it]

Collecting articles for category: Ecosystems

Collecting articles:  29%|██▉       | 66/227 [03:45<09:50,  3.67s/it]

Collecting articles for category: Emotions

Collecting articles:  30%|██▉       | 67/227 [03:49<10:36,  3.98s/it]

Collecting articles for category: Engineering

Collecting articles:  30%|██▉       | 68/227 [03:56<12:21,  4.66s/it]

Collecting articles for category: Entomology

Collecting articles:  30%|███       | 69/227 [03:59<11:02,  4.19s/it]

Collecting articles for category: Epidemiology

Collecting articles:  31%|███       | 70/227 [04:01<09:50,  3.76s/it]

Collecting articles for category: Establishments

Collecting articles:  31%|███▏      | 71/227 [04:03<08:07,  3.12s/it]

Collecting articles for category: Ethnocentrism

Collecting articles:  32%|███▏      | 72/227 [04:06<08:10,  3.17s/it]

Collecting articles for category: Ethology

Collecting articles:  32%|███▏      | 73/227 [04:10<08:21,  3.26s/it]

Collecting articles for category: Eukaryotes

Collecting articles:  33%|███▎      | 74/227 [04:13<08:00,  3.14s/it]

Collecting articles for category: Extinction

Collecting articles:  33%|███▎      | 75/227 [04:16<08:09,  3.22s/it]

Collecting articles for category: Extremophiles

Collecting articles:  33%|███▎      | 76/227 [04:19<07:54,  3.14s/it]

Collecting articles for category: Fertilizers

Collecting articles:  34%|███▍      | 77/227 [04:22<07:47,  3.12s/it]

Collecting articles for category: Fire

Collecting articles:  34%|███▍      | 78/227 [04:25<07:52,  3.17s/it]

Collecting articles for category: Firefighting

Collecting articles:  35%|███▍      | 79/227 [04:28<07:48,  3.17s/it]

Collecting articles for category: Fires

Collecting articles:  35%|███▌      | 80/227 [04:32<07:53,  3.22s/it]

Collecting articles for category: Flags

Collecting articles:  36%|███▌      | 81/227 [04:35<07:58,  3.28s/it]

Collecting articles for category: Flatworms

Collecting articles:  36%|███▌      | 82/227 [04:39<07:55,  3.28s/it]

Collecting articles for category: Forestry

Collecting articles:  37%|███▋      | 83/227 [04:41<07:35,  3.16s/it]

Collecting articles for category: Forests

Collecting articles:  37%|███▋      | 84/227 [04:44<07:18,  3.07s/it]

Collecting articles for category: Frogs

Collecting articles:  37%|███▋      | 85/227 [04:48<07:29,  3.16s/it]

Collecting articles for category: Fungi

Collecting articles:  38%|███▊      | 86/227 [04:52<08:28,  3.61s/it]

Collecting articles for category: Gardening

Collecting articles:  38%|███▊      | 87/227 [04:55<08:03,  3.45s/it]

Collecting articles for category: Gardens

Collecting articles:  39%|███▉      | 88/227 [04:59<07:51,  3.39s/it]

Collecting articles for category: Gemstones

Collecting articles:  39%|███▉      | 89/227 [05:02<07:29,  3.26s/it]

Collecting articles for category: Genetics

Collecting articles:  40%|███▉      | 90/227 [05:06<08:18,  3.64s/it]

Collecting articles for category: Giftedness

Collecting articles:  40%|████      | 91/227 [05:09<07:54,  3.49s/it]

Collecting articles for category: Glaciers

Collecting articles:  41%|████      | 92/227 [05:12<07:37,  3.39s/it]

Collecting articles for category: Glass

Collecting articles:  41%|████      | 93/227 [05:15<07:21,  3.29s/it]

Collecting articles for category: Goods

Collecting articles:  41%|████▏     | 94/227 [05:18<07:06,  3.21s/it]

Collecting articles for category: Graphics

Collecting articles:  42%|████▏     | 95/227 [05:22<07:04,  3.21s/it]

Collecting articles for category: Grasslands

Collecting articles:  42%|████▏     | 96/227 [05:25<06:46,  3.10s/it]

Collecting articles for category: Happiness

Collecting articles:  43%|████▎     | 97/227 [05:27<06:31,  3.01s/it]

Collecting articles for category: Herbicides

Collecting articles:  43%|████▎     | 98/227 [05:31<06:40,  3.11s/it]

Collecting articles for category: Hippopotamuses

Collecting articles:  44%|████▎     | 99/227 [05:34<06:35,  3.09s/it]

Collecting articles for category: Historiography

Collecting articles:  44%|████▍     | 100/227 [05:37<06:29,  3.07s/it]

Collecting articles for category: History

Collecting articles:  44%|████▍     | 101/227 [05:40<06:37,  3.15s/it]

Collecting articles for category: Hydropower

Collecting articles:  45%|████▍     | 102/227 [05:44<06:46,  3.25s/it]

Collecting articles for category: Illusions

Collecting articles:  45%|████▌     | 103/227 [05:46<06:30,  3.15s/it]

Collecting articles for category: Infrastructure

Collecting articles:  46%|████▌     | 104/227 [05:50<06:23,  3.12s/it]

Collecting articles for category: Innovation

Collecting articles:  46%|████▋     | 105/227 [05:53<06:25,  3.16s/it]

Collecting articles for category: Insecticides

Collecting articles:  47%|████▋     | 106/227 [05:56<06:08,  3.04s/it]

Collecting articles for category: Insects

Collecting articles:  47%|████▋     | 107/227 [06:01<07:15,  3.63s/it]

Collecting articles for category: Intelligence

Collecting articles:  48%|████▊     | 108/227 [06:04<06:53,  3.48s/it]

Collecting articles for category: Invertebrates

Collecting articles:  48%|████▊     | 109/227 [06:07<06:34,  3.34s/it]

Collecting articles for category: Journalism

Collecting articles:  48%|████▊     | 110/227 [06:10<06:25,  3.29s/it]

Collecting articles for category: Kinematics

Collecting articles:  49%|████▉     | 111/227 [06:13<06:06,  3.16s/it]

Collecting articles for category: Learning

Collecting articles:  49%|████▉     | 112/227 [06:16<06:07,  3.20s/it]

Collecting articles for category: Light

Collecting articles:  50%|████▉     | 113/227 [06:19<05:57,  3.14s/it]

Collecting articles for category: Lighthouses

Collecting articles:  50%|█████     | 114/227 [06:22<06:01,  3.20s/it]

Collecting articles for category: Lighting

Collecting articles:  51%|█████     | 115/227 [06:25<05:50,  3.13s/it]

Collecting articles for category: Linguistics

Collecting articles:  51%|█████     | 116/227 [06:30<06:42,  3.62s/it]

Collecting articles for category: Literature

Collecting articles:  52%|█████▏    | 117/227 [06:33<06:23,  3.48s/it]

Collecting articles for category: Logic

Collecting articles:  52%|█████▏    | 118/227 [06:38<07:03,  3.88s/it]

Collecting articles for category: Love

Collecting articles:  52%|█████▏    | 119/227 [06:41<06:35,  3.66s/it]

Collecting articles for category: Machines

Collecting articles:  53%|█████▎    | 120/227 [06:46<07:06,  3.99s/it]

Collecting articles for category: Mammals

Collecting articles:  53%|█████▎    | 121/227 [06:50<07:12,  4.08s/it]

Collecting articles for category: Manga

Collecting articles:  54%|█████▎    | 122/227 [06:55<07:39,  4.37s/it]

Collecting articles for category: Manufacturing

Collecting articles:  54%|█████▍    | 123/227 [06:58<06:50,  3.95s/it]

Collecting articles for category: Manuscripts

Collecting articles:  55%|█████▍    | 124/227 [07:02<06:32,  3.81s/it]

Collecting articles for category: Mascots

Collecting articles:  55%|█████▌    | 125/227 [07:05<06:03,  3.57s/it]

Collecting articles for category: Materials

Collecting articles:  56%|█████▌    | 126/227 [07:08<05:46,  3.44s/it]

Collecting articles for category: Mathematics

Collecting articles:  56%|█████▌    | 127/227 [07:16<07:49,  4.69s/it]

Collecting articles for category: Mechanics

Collecting articles:  56%|█████▋    | 128/227 [07:20<07:52,  4.77s/it]

Collecting articles for category: Medicine

Collecting articles:  57%|█████▋    | 129/227 [07:27<08:34,  5.25s/it]

Collecting articles for category: Mesonychids

Collecting articles:  57%|█████▋    | 130/227 [07:30<07:23,  4.57s/it]

Collecting articles for category: Metalworking

Collecting articles:  58%|█████▊    | 131/227 [07:33<06:35,  4.12s/it]

Collecting articles for category: Microbiology

Collecting articles:  58%|█████▊    | 132/227 [07:36<05:58,  3.77s/it]

Collecting articles for category: Migraine

Collecting articles:  59%|█████▊    | 133/227 [07:39<05:32,  3.53s/it]

Collecting articles for category: Millennia

Collecting articles:  59%|█████▉    | 134/227 [07:42<05:16,  3.40s/it]

Collecting articles for category: Modernism

Collecting articles:  59%|█████▉    | 135/227 [07:46<05:42,  3.72s/it]

Collecting articles for category: Modernity

Collecting articles:  60%|█████▉    | 136/227 [07:49<05:18,  3.50s/it]

Collecting articles for category: Molluscs

Collecting articles:  60%|██████    | 137/227 [07:52<04:58,  3.31s/it]

Collecting articles for category: Months

Collecting articles:  61%|██████    | 138/227 [07:55<04:43,  3.19s/it]

Collecting articles for category: Mosaics

Collecting articles:  61%|██████    | 139/227 [07:58<04:28,  3.05s/it]

Collecting articles for category: Museums

Collecting articles:  62%|██████▏   | 140/227 [08:01<04:29,  3.10s/it]

Collecting articles for category: Music

Collecting articles:  62%|██████▏   | 141/227 [08:04<04:33,  3.18s/it]

Collecting articles for category: Narcissism

Collecting articles:  63%|██████▎   | 142/227 [08:07<04:19,  3.06s/it]

Collecting articles for category: Nematodes

Collecting articles:  63%|██████▎   | 143/227 [08:10<04:10,  2.98s/it]

Collecting articles for category: Neuropsychology

Collecting articles:  63%|██████▎   | 144/227 [08:13<04:14,  3.07s/it]

Collecting articles for category: Neuroscience

Collecting articles:  64%|██████▍   | 145/227 [08:17<04:17,  3.14s/it]

Collecting articles for category: Newts

Collecting articles:  64%|██████▍   | 146/227 [08:20<04:14,  3.14s/it]

Collecting articles for category: Nucleotides

Collecting articles:  65%|██████▍   | 147/227 [08:23<04:06,  3.09s/it]

Collecting articles for category: Observances

Collecting articles:  65%|██████▌   | 148/227 [08:26<03:59,  3.03s/it]

Collecting articles for category: Observation

Collecting articles:  66%|██████▌   | 149/227 [08:29<03:55,  3.02s/it]

Collecting articles for category: Opera

Collecting articles:  66%|██████▌   | 150/227 [08:32<03:53,  3.03s/it]

Collecting articles for category: Operas

Collecting articles:  67%|██████▋   | 151/227 [08:35<03:54,  3.08s/it]

Collecting articles for category: Optoelectronics

Collecting articles:  67%|██████▋   | 152/227 [08:38<03:55,  3.14s/it]

Collecting articles for category: Organisms

Collecting articles:  67%|██████▋   | 153/227 [08:42<03:59,  3.24s/it]

Collecting articles for category: Oscillation

Collecting articles:  68%|██████▊   | 154/227 [08:45<03:51,  3.17s/it]

Collecting articles for category: Pain

Collecting articles:  68%|██████▊   | 155/227 [08:47<03:39,  3.04s/it]

Collecting articles for category: Paints

Collecting articles:  69%|██████▊   | 156/227 [08:50<03:32,  3.00s/it]

Collecting articles for category: Pamphlets

Collecting articles:  69%|██████▉   | 157/227 [08:53<03:33,  3.05s/it]

Collecting articles for category: Parades

Collecting articles:  70%|██████▉   | 158/227 [08:56<03:30,  3.05s/it]

Collecting articles for category: Parasites

Collecting articles:  70%|███████   | 159/227 [09:00<03:28,  3.06s/it]

Collecting articles for category: Parrots

Collecting articles:  70%|███████   | 160/227 [09:03<03:28,  3.11s/it]

Collecting articles for category: Pendulums

Collecting articles:  71%|███████   | 161/227 [09:06<03:28,  3.15s/it]

Collecting articles for category: Perception

Collecting articles:  71%|███████▏  | 162/227 [09:09<03:18,  3.06s/it]

Collecting articles for category: Pesticides

Collecting articles:  72%|███████▏  | 163/227 [09:12<03:22,  3.16s/it]

Collecting articles for category: Pharmacology

Collecting articles:  72%|███████▏  | 164/227 [09:15<03:18,  3.15s/it]

Collecting articles for category: Phenomena

Collecting articles:  73%|███████▎  | 165/227 [09:19<03:21,  3.25s/it]

Collecting articles for category: Philosophy

Collecting articles:  73%|███████▎  | 166/227 [09:25<04:17,  4.23s/it]

Collecting articles for category: Phobias

Collecting articles:  74%|███████▎  | 167/227 [09:29<03:54,  3.90s/it]

Collecting articles for category: Photovoltaics

Collecting articles:  74%|███████▍  | 168/227 [09:31<03:29,  3.55s/it]

Collecting articles for category: Physics

Collecting articles:  74%|███████▍  | 169/227 [09:38<04:15,  4.40s/it]

Collecting articles for category: Plays

Collecting articles:  75%|███████▍  | 170/227 [09:41<03:44,  3.94s/it]

Collecting articles for category: Poisons

Collecting articles:  75%|███████▌  | 171/227 [09:44<03:30,  3.77s/it]

Collecting articles for category: Pottery

Collecting articles:  76%|███████▌  | 172/227 [09:47<03:13,  3.52s/it]

Collecting articles for category: Profanity

Collecting articles:  76%|███████▌  | 173/227 [09:50<03:05,  3.43s/it]

Collecting articles for category: Prokaryotes

Collecting articles:  77%|███████▋  | 174/227 [09:53<02:59,  3.38s/it]

Collecting articles for category: Psychology

Collecting articles:  77%|███████▋  | 175/227 [10:03<04:37,  5.33s/it]

Collecting articles for category: Publications

Collecting articles:  78%|███████▊  | 176/227 [10:06<03:59,  4.70s/it]

Collecting articles for category: Punctuation

Collecting articles:  78%|███████▊  | 177/227 [10:10<03:34,  4.30s/it]

Collecting articles for category: Rainforests

Collecting articles:  78%|███████▊  | 178/227 [10:13<03:14,  3.97s/it]

Collecting articles for category: Rationalism

Collecting articles:  79%|███████▉  | 179/227 [10:16<03:00,  3.76s/it]

Collecting articles for category: Reasoning

Collecting articles:  79%|███████▉  | 180/227 [10:20<02:50,  3.63s/it]

Collecting articles for category: Reptiles

Collecting articles:  80%|███████▉  | 181/227 [10:23<02:40,  3.48s/it]

Collecting articles for category: Rhetoric

Collecting articles:  80%|████████  | 182/227 [10:26<02:32,  3.39s/it]

Collecting articles for category: Robots

Collecting articles:  81%|████████  | 183/227 [10:29<02:25,  3.32s/it]

Collecting articles for category: Salamanders

Collecting articles:  81%|████████  | 184/227 [10:33<02:24,  3.36s/it]

Collecting articles for category: Salamandridae

Collecting articles:  81%|████████▏ | 185/227 [10:36<02:21,  3.38s/it]

Collecting articles for category: Satellites

Collecting articles:  82%|████████▏ | 186/227 [10:39<02:13,  3.26s/it]

Collecting articles for category: Scorpius

Collecting articles:  82%|████████▏ | 187/227 [10:42<02:04,  3.12s/it]

Collecting articles for category: Seasons

Collecting articles:  83%|████████▎ | 188/227 [10:45<02:00,  3.08s/it]

Collecting articles for category: Semiconductors

Collecting articles:  83%|████████▎ | 189/227 [10:48<01:55,  3.05s/it]

Collecting articles for category: Smartwatches

Collecting articles:  84%|████████▎ | 190/227 [10:51<01:54,  3.10s/it]

Collecting articles for category: Snow

Collecting articles:  84%|████████▍ | 191/227 [10:54<01:53,  3.16s/it]

Collecting articles for category: Sociology

Collecting articles:  85%|████████▍ | 192/227 [11:00<02:20,  4.02s/it]

Collecting articles for category: Software

Collecting articles:  85%|████████▌ | 193/227 [11:10<03:11,  5.64s/it]

Collecting articles for category: Spacecraft

Collecting articles:  85%|████████▌ | 194/227 [11:13<02:40,  4.85s/it]

Collecting articles for category: Spaceflight

Collecting articles:  86%|████████▌ | 195/227 [11:16<02:17,  4.30s/it]

Collecting articles for category: Sponges

Collecting articles:  86%|████████▋ | 196/227 [11:19<02:00,  3.88s/it]

Collecting articles for category: Statistics

Collecting articles:  87%|████████▋ | 197/227 [11:24<02:06,  4.20s/it]

Collecting articles for category: Submarines

Collecting articles:  87%|████████▋ | 198/227 [11:27<01:53,  3.90s/it]

Collecting articles for category: Surgery

Collecting articles:  88%|████████▊ | 199/227 [11:32<01:58,  4.22s/it]

Collecting articles for category: Surrealism

Collecting articles:  88%|████████▊ | 200/227 [11:34<01:42,  3.78s/it]

Collecting articles for category: Symbols

Collecting articles:  89%|████████▊ | 201/227 [11:39<01:44,  4.01s/it]

Collecting articles for category: Television

Collecting articles:  89%|████████▉ | 202/227 [11:44<01:47,  4.30s/it]

Collecting articles for category: Tetrapods

Collecting articles:  89%|████████▉ | 203/227 [11:47<01:33,  3.91s/it]

Collecting articles for category: Theatre

Collecting articles:  90%|████████▉ | 204/227 [11:50<01:25,  3.70s/it]

Collecting articles for category: Theatres

Collecting articles:  90%|█████████ | 205/227 [11:53<01:17,  3.50s/it]

Collecting articles for category: Theism

Collecting articles:  91%|█████████ | 206/227 [11:56<01:09,  3.29s/it]

Collecting articles for category: Theology

Collecting articles:  91%|█████████ | 207/227 [12:01<01:15,  3.79s/it]

Collecting articles for category: Toads

Collecting articles:  92%|█████████▏| 208/227 [12:06<01:16,  4.05s/it]

Collecting articles for category: Tourism

Collecting articles:  92%|█████████▏| 209/227 [12:09<01:06,  3.69s/it]

Collecting articles for category: Training

Collecting articles:  93%|█████████▎| 210/227 [12:12<01:00,  3.57s/it]

Collecting articles for category: Treaties

Collecting articles:  93%|█████████▎| 211/227 [12:15<00:56,  3.55s/it]

Collecting articles for category: Tropes

Collecting articles:  93%|█████████▎| 212/227 [12:18<00:50,  3.40s/it]

Collecting articles for category: Turtles

Collecting articles:  94%|█████████▍| 213/227 [12:21<00:45,  3.26s/it]

Collecting articles for category: Ungulates

Collecting articles:  94%|█████████▍| 214/227 [12:24<00:40,  3.12s/it]

Collecting articles for category: Vaccines

Collecting articles:  95%|█████████▍| 215/227 [12:28<00:39,  3.31s/it]

Collecting articles for category: Vehicles

Collecting articles:  95%|█████████▌| 216/227 [12:31<00:37,  3.38s/it]

Collecting articles for category: Vultures

Collecting articles:  96%|█████████▌| 217/227 [12:35<00:33,  3.37s/it]

Collecting articles for category: Watches

Collecting articles:  96%|█████████▌| 218/227 [12:36<00:25,  2.86s/it]

Collecting articles for category: Water

Collecting articles:  96%|█████████▋| 219/227 [12:41<00:26,  3.37s/it]

Collecting articles for category: Waves

Collecting articles:  97%|█████████▋| 220/227 [12:44<00:23,  3.29s/it]

Collecting articles for category: Wetlands

Collecting articles:  97%|█████████▋| 221/227 [12:47<00:19,  3.24s/it]

Collecting articles for category: Wolves

Collecting articles:  98%|█████████▊| 222/227 [12:50<00:16,  3.26s/it]

Collecting articles for category: Woodworking

Collecting articles:  98%|█████████▊| 223/227 [12:54<00:12,  3.21s/it]

Collecting articles for category: Xenacoelomorpha

Collecting articles:  99%|█████████▊| 224/227 [12:57<00:09,  3.27s/it]

Collecting articles for category: Xenophobia

Collecting articles:  99%|█████████▉| 225/227 [13:00<00:06,  3.18s/it]

Collecting articles for category: Years

Collecting articles: 100%|█████████▉| 226/227 [13:03<00:03,  3.07s/it]

Collecting articles for category: Zoology

Collecting articles: 100%|██████████| 227/227 [13:06<00:00,  3.46s/it]

Collected 6073 category-title pairs.

In [17]:
matched_pairs

[{'category': 'Acceleration', 'title': 'Acceleration'},
 {'category': 'Acceleration', 'title': 'Accelerometer'},
 {'category': 'Acceleration', 'title': 'Centrifugal force'},
 {'category': 'Acceleration', 'title': 'Centripetal force'},
 {'category': 'Acceleration', 'title': 'Gravity'},
 {'category': 'Acceleration', 'title': 'G-force'},
 {'category': 'Adhesives', 'title': 'Adhesion'},
 {'category': 'Adhesives', 'title': 'Adhesive'},
 {'category': 'Adhesives', 'title': 'Binder (material)'},
 {'category': 'Adhesives', 'title': 'Epoxy'},
 {'category': 'Adhesives', 'title': 'Sticker'},
 {'category': 'Adhesives', 'title': 'Cyanoacrylate'},
 {'category': 'Adhesives', 'title': 'Thickening agent'},
 {'category': 'Algae', 'title': 'Algae'},
 {'category': 'Algae', 'title': 'Algal bloom'},
 {'category': 'Algae', 'title': 'Brown algae'},
 {'category': 'Algae', 'title': 'Charophyceae'},
 {'category': 'Algae', 'title': 'Chlorella'},
 {'category': 'Algae', 'title': 'Chlorophyta'},
 {'category': 'Algae', 'title': 'Coccolith'},
 {'category': 'Algae', 'title': 'Cryptista'},
 {'category': 'Algae', 'title': 'Cryptomonad'},
 {'category': 'Algae', 'title': 'Diaphoretickes'},
 {'category': 'Algae', 'title': 'Diatom'},
 {'category': 'Algae', 'title': 'Didymosphenia geminata'},
 {'category': 'Algae', 'title': 'Dinoflagellate'},
 {'category': 'Algae', 'title': 'Dunaliella salina'},
 {'category': 'Algae', 'title': 'Glaucophyte'},
 {'category': 'Algae', 'title': 'Golden algae'},
 {'category': 'Algae', 'title': 'Green algae'},
 {'category': 'Algae', 'title': 'Grypania'},
 {'category': 'Algae', 'title': 'Haptophyte'},
 {'category': 'Algae', 'title': 'Ice algae'},
 {'category': 'Algae', 'title': 'Kelp'},
 {'category': 'Algae', 'title': 'Letharia'},
 {'category': 'Algae', 'title': 'Letharia vulpina'},
 {'category': 'Algae', 'title': 'Lichen'},
 {'category': 'Algae', 'title': 'Lingulodinium polyedra'},
 {'category': 'Algae', 'title': 'Mesostigmatophyceae'},
 {'category': 'Algae', 'title': 'Phycology'},
 {'category': 'Algae', 'title': 'Red algae'},
 {'category': 'Algae', 'title': 'Sargassum'},
 {'category': 'Algae', 'title': 'Seaweed'},
 {'category': 'Algae', 'title': 'Stramenopile'},
 {'category': 'Algae', 'title': 'Ulvaceae'},
 {'category': 'Algae', 'title': 'Ulvales'},
 {'category': 'Algae', 'title': 'Ulvophyceae'},
 {'category': 'Algae', 'title': 'Valonia ventricosa'},
 {'category': 'Algae', 'title': 'Wakame'},
 {'category': 'Algae', 'title': 'Yellow-green algae'},
 {'category': 'Algae', 'title': 'Zygnemataceae'},
 {'category': 'Algae', 'title': 'Zygnematales'},
 {'category': 'Algae', 'title': 'Zygnematophyceae'},
 {'category': 'Algae', 'title': 'Chromalveolata'},
 {'category': 'Amphibians', 'title': 'Amphibian'},
 {'category': 'Amphibians', 'title': 'Diplocaulus'},
 {'category': 'Amphibians', 'title': 'Herpetology'},
 {'category': 'Amphibians', 'title': 'Hydric brooding'},
 {'category': 'Amphibians', 'title': 'Lissamphibia'},
 {'category': 'Amphibians', 'title': 'List of amphibians'},
 {'category': 'Amphibians', 'title': 'List of amphibians of Russia'},
 {'category': 'Amphibians', 'title': 'Liurana'},
 {'category': 'Amphibians', 'title': 'Mental gland'},
 {'category': 'Amphibians', 'title': 'Nuptial pad'},
 {'category': 'Amphibians', 'title': 'Olm'},
 {'category': 'Amphibians', 'title': 'Parotoid gland'},
 {'category': 'Amphibians', 'title': 'Reptiliomorpha'},
 {'category': 'Amphibians', 'title': 'Seymouria'},
 {'category': 'Amphibians', 'title': 'Labyrinthodontia'},
 {'category': 'Amphibians', 'title': 'Lepospondyli'},
 {'category': 'Amphibians', 'title': 'List of frogs and toads of New Jersey'},
 {'category': 'Amphibians', 'title': 'Snout–vent length'},
 {'category': 'Amphibians', 'title': 'Spawning'},
 {'category': 'Angels', 'title': 'Angel'},
 {'category': 'Angels', 'title': 'Azrael'},
 {'category': 'Angels', 'title': 'Fallen angel'},
 {'category': 'Angels', 'title': 'Gabriel'},
 {'category': 'Angels', 'title': 'Harut and Marut'},
 {'category': 'Angels', 'title': 'Iblis'},
 {'category': 'Angels', 'title': 'Michael (archangel)'},
 {'category': 'Angels', 'title': 'Moroni'},
 {'category': 'Angels', 'title': 'Nephilim'},
 {'category': 'Angels', 'title': 'Raphael (archangel)'},
 {'category': 'Angels', 'title': 'Samael'},
 {'category': 'Angels', 'title': 'Satan'},
 {'category': 'Angels', 'title': 'Uriel'},
 {'category': 'Angels', 'title': 'Yōkai'},
 {'category': 'Animals', 'title': 'Amphibian'},
 {'category': 'Animals', 'title': 'Animal'},
 {'category': 'Animals', 'title': 'Arthropod'},
 {'category': 'Animals', 'title': 'Bilateria'},
 {'category': 'Animals', 'title': 'Chordate'},
 {'category': 'Animals', 'title': 'Deuterostome'},
 {'category': 'Animals', 'title': 'Earthworm'},
 {'category': 'Animals', 'title': 'Ecdysozoa'},
 {'category': 'Animals', 'title': 'Eumetazoa'},
 {'category': 'Animals', 'title': 'Feral'},
 {'category': 'Animals', 'title': 'Fish'},
 {'category': 'Animals', 'title': 'Gnathostomata'},
 {'category': 'Animals', 'title': 'Hemipristis'},
 {'category': 'Animals', 'title': 'Holocene extinction'},
 {'category': 'Animals', 'title': 'Insect'},
 {'category': 'Animals', 'title': 'Invertebrate'},
 {'category': 'Animals', 'title': 'Mammal'},
 {'category': 'Animals', 'title': 'ParaHoxozoa'},
 {'category': 'Animals', 'title': 'Pet'},
 {'category': 'Animals', 'title': 'Phoronopsis'},
 {'category': 'Animals', 'title': 'Protostome'},
 {'category': 'Animals', 'title': 'Radiata'},
 {'category': 'Animals', 'title': 'Scrotifera'},
 {'category': 'Animals', 'title': 'Spider'},
 {'category': 'Animals', 'title': 'Tactopoda'},
 {'category': 'Animals', 'title': 'Thaliacea'},
 {'category': 'Animals', 'title': 'Tribrachidium'},
 {'category': 'Animals', 'title': 'Tullimonstrum'},
 {'category': 'Animals', 'title': 'Vertebrate'},
 {'category': 'Animals', 'title': 'Xenacoelomorpha'},
 {'category': 'Animals', 'title': 'Xerocole'},
 {'category': 'Animals', 'title': 'Zanclean'},
 {'category': 'Animals', 'title': 'Sponge'},
 {'category': 'Annelids', 'title': 'Alitta succinea'},
 {'category': 'Annelids', 'title': 'Annelid'},
 {'category': 'Annelids', 'title': 'Antillesoma'},
 {'category': 'Annelids', 'title': 'Antillesoma antillarum'},
 {'category': 'Annelids', 'title': 'Branchiobdellida'},
 {'category': 'Annelids', 'title': 'Earthworm'},
 {'category': 'Annelids', 'title': 'Echiura'},
 {'category': 'Annelids', 'title': 'Eunice aphroditois'},
 {'category': 'Annelids', 'title': 'Giant Gippsland earthworm'},
 {'category': 'Annelids', 'title': 'Lamellibrachia'},
 {'category': 'Annelids', 'title': 'Leech'},
 {'category': 'Annelids', 'title': 'Lumbriculus variegatus'},
 {'category': 'Annelids', 'title': 'Lumbricus terrestris'},
 {'category': 'Annelids', 'title': 'Polychaete'},
 {'category': 'Annelids', 'title': 'Sipuncula'},
 {'category': 'Annelids', 'title': 'Arenicola'},
 {'category': 'Annelids', 'title': 'Oligochaeta'},
 {'category': 'Annelids', 'title': 'Riftia'},
 {'category': 'Anthropology', 'title': 'Anthropology'},
 {'category': 'Anthropology', 'title': 'Anthropometry'},
 {'category': 'Anthropology', 'title': 'Behavioral modernity'},
 {'category': 'Anthropology', 'title': 'Civilization'},
 {'category': 'Anthropology', 'title': 'Cultural artifact'},
 {'category': 'Anthropology', 'title': 'Cultural system'},
 {'category': 'Anthropology', 'title': 'Culture shock'},
 {'category': 'Anthropology', 'title': 'Division of labour'},
 {'category': 'Anthropology', 'title': 'Economy-of-effort theory'},
 {'category': 'Anthropology', 'title': 'Ethnography'},
 {'category': 'Anthropology', 'title': 'Feminist anthropology'},
 {'category': 'Anthropology', 'title': 'Forensic anthropology'},
 {'category': 'Anthropology', 'title': 'Fosterage'},
 {'category': 'Anthropology', 'title': 'Four-field approach'},
 {'category': 'Anthropology', 'title': 'Functionalism (philosophy of mind)'},
 {'category': 'Anthropology', 'title': 'Gebelein predynastic mummies'},
 {'category': 'Anthropology', 'title': 'Gendered racism'},
 {'category': 'Anthropology', 'title': 'Genocide'},
 {'category': 'Anthropology', 'title': 'Grave goods'},
 {'category': 'Anthropology', 'title': 'Hand axe'},
 {'category': 'Anthropology', 'title': 'Historical race concepts'},
 {'category': 'Anthropology', 'title': 'Human biology'},
 {'category': 'Anthropology', 'title': 'Human evolution'},
 {'category': 'Anthropology', 'title': 'Hunter-gatherer'},
 {'category': 'Anthropology', 'title': 'Ishi in Two Worlds'},
 {'category': 'Anthropology', 'title': 'Linguistic anthropology'},
 {'category': 'Anthropology', 'title': 'Meme'},
 {'category': 'Anthropology', 'title': 'Nerd'},
 {'category': 'Anthropology', 'title': 'Nuclear family'},
 {'category': 'Anthropology', 'title': 'Participant observation'},
 {'category': 'Anthropology', 'title': 'People-watching'},
 {'category': 'Anthropology', 'title': 'Primatology'},
 {'category': 'Anthropology', 'title': 'Prognathism'},
 {'category': 'Anthropology', 'title': 'Robert Broom'},
 {'category': 'Anthropology', 'title': 'Sarah Baartman'},
 {'category': 'Anthropology', 'title': 'Settler'},
 {'category': 'Anthropology', 'title': 'Shrunken head'},
 {'category': 'Anthropology', 'title': 'Skepticism'},
 {'category': 'Anthropology', 'title': 'Social anthropology'},
 {'category': 'Anthropology', 'title': 'Symbolic anthropology'},
 {'category': 'Anthropology', 'title': 'Unilineal evolution'},
 {'category': 'Anthropology', 'title': 'Artificiality'},
 {'category': 'Anthropology', 'title': 'Gorgons'},
 {'category': 'Anthropology', 'title': 'Paleolithic'},
 {'category': 'Anthropology', 'title': 'Scientific racism'},
 {'category': 'Anthropology', 'title': 'Totem'},
 {'category': 'Anthropology', 'title': "Trapper's cache"},
 {'category': 'Anthropology', 'title': 'Ötzi'},
 {'category': 'Anthropology', 'title': 'Sápara'},
 {'category': 'Antisemitism', 'title': 'Antisemitism'},
 {'category': 'Antisemitism', 'title': 'Antisemitism in the Soviet Union'},
 {'category': 'Antisemitism', 'title': 'Bergen-Belsen concentration camp'},
 {'category': 'Antisemitism', 'title': 'Black Hebrew Israelites'},
 {'category': 'Antisemitism', 'title': 'Buchenwald concentration camp'},
 {'category': 'Antisemitism', 'title': 'Clerical fascism'},
 {'category': 'Antisemitism', 'title': 'Cultural Marxism conspiracy theory'},
 {'category': 'Antisemitism', 'title': 'Dachau concentration camp'},
 {'category': 'Antisemitism', 'title': 'David Irving'},
 {'category': 'Antisemitism', 'title': 'Faithful Word Baptist Church'},
 {'category': 'Antisemitism', 'title': 'Far-right politics'},
 {'category': 'Antisemitism', 'title': 'Ghetto'},
 {'category': 'Antisemitism', 'title': 'Good Friday prayer for the Jews'},
 {'category': 'Antisemitism', 'title': 'Goyim Defense League'},
 {'category': 'Antisemitism', 'title': 'Happy Merchant'},
 {'category': 'Antisemitism', 'title': 'Historical revisionism'},
 {'category': 'Antisemitism', 'title': 'Holocaust trivialization'},
 {'category': 'Antisemitism', 'title': 'Holocaust uniqueness debate'},
 {'category': 'Antisemitism', 'title': 'Inquisition'},
 {'category': 'Antisemitism',
  'title': 'International Holocaust Remembrance Alliance'},
 {'category': 'Antisemitism', 'title': 'Ion Antonescu'},
 {'category': 'Antisemitism', 'title': 'Jewish deicide'},
 {'category': 'Antisemitism', 'title': 'Joseph Goebbels'},
 {'category': 'Antisemitism', 'title': 'Judeo-Masonic conspiracy theory'},
 {'category': 'Antisemitism', 'title': 'Judeopolonia'},
 {'category': 'Antisemitism', 'title': 'Kampfbund'},
 {'category': 'Antisemitism', 'title': 'Khaybar Khaybar ya yahud'},
 {'category': 'Antisemitism', 'title': 'List of Nazi concentration camps'},
 {'category': 'Antisemitism', 'title': 'Louis Farrakhan'},
 {'category': 'Antisemitism', 'title': 'Martin Luther'},
 {'category': 'Antisemitism', 'title': 'Mas-Kom-Yah'},
 {'category': 'Antisemitism', 'title': 'Nicolas Anelka'},
 {'category': 'Antisemitism', 'title': 'Subhas Chandra Bose'},
 {'category': 'Antisemitism', 'title': 'The Holocaust'},
 {'category': 'Antisemitism', 'title': 'Antisemitic trope'},
 {'category': 'Antisemitism', 'title': 'Antisemitism in Europe'},
 {'category': 'Antisemitism', 'title': 'Birthday (disambiguation)'},
 {'category': 'Antisemitism', 'title': 'Dreyfus affair'},
 {'category': 'Antisemitism', 'title': 'History of the Jews in Ireland'},
 {'category': 'Antisemitism', 'title': 'Joshua N. Haldeman'},
 {'category': 'Antisemitism',
  'title': 'Khazar hypothesis of Ashkenazi ancestry'},
 {'category': 'Antisemitism', 'title': 'Legitimacy of the State of Israel'},
 {'category': 'Antisemitism', 'title': 'Kanye West'},
 {'category': 'Antisemitism', 'title': 'Konstantin von Neurath'},
 {'category': 'Antisemitism', 'title': 'Mein Kampf'},
 {'category': 'Antisemitism', 'title': 'Nation of Islam'},
 {'category': 'Antisemitism', 'title': 'Nazi Germany'},
 {'category': 'Antisemitism', 'title': 'Nazism'},
 {'category': 'Antisemitism', 'title': 'Palestinian political violence'},
 {'category': 'Antisemitism', 'title': 'Pittsburgh synagogue shooting'},
 {'category': 'Antisemitism', 'title': 'Queers Undermining Israeli Terrorism'},
 {'category': 'Antisemitism', 'title': 'Qutbism'},
 {'category': 'Antisemitism', 'title': 'Red Jews'},
 {'category': 'Antisemitism', 'title': 'Richard C. Lukas'},
 {'category': 'Antisemitism', 'title': 'Sachsenhausen concentration camp'},
 {'category': 'Antisemitism', 'title': 'Secondary antisemitism'},
 {'category': 'Antisemitism', 'title': 'Self-hating Jew'},
 {'category': 'Antisemitism', 'title': 'Society of Saint Pius X'},
 {'category': 'Antisemitism', 'title': 'Spanish Inquisition'},
 {'category': 'Antisemitism', 'title': 'StopAntisemitism'},
 {'category': 'Antisemitism', 'title': 'Supersessionism'},
 {'category': 'Antisemitism', 'title': 'The Merchant of Venice'},
 {'category': 'Antisemitism', 'title': 'The Protocols of the Elders of Zion'},
 {'category': 'Antisemitism', 'title': 'Tomás de Torquemada'},
 {'category': 'Antisemitism', 'title': 'Untermensch'},
 {'category': 'Antisemitism', 'title': 'White nationalism'},
 {'category': 'Antisemitism', 'title': '1941 Odessa massacre'},
 {'category': 'Antisemitism', 'title': 'White genocide conspiracy theory'},
 {'category': 'Aquariums', 'title': 'Airstone'},
 {'category': 'Aquariums', 'title': 'Aquarium'},
 {'category': 'Aquariums', 'title': 'Aquarium Barcelona'},
 {'category': 'Aquariums', 'title': 'Aquarium of the Pacific'},
 {'category': 'Aquariums', 'title': 'Georgia Aquarium'},
 {'category': 'Aquariums',
  'title': 'List of ornamental aquatic plants in Venezuela'},
 {'category': 'Aquariums', 'title': 'Livebearers'},
 {'category': 'Aquariums', 'title': 'Miami Seaquarium'},
 {'category': 'Aquariums', 'title': 'Newport Aquarium'},
 {'category': 'Aquariums', 'title': 'Shedd Aquarium'},
 {'category': 'Aquariums', 'title': 'Stanley Park'},
 {'category': 'Aquariums', 'title': 'Hand net'},
 {'category': 'Aquariums', 'title': 'SeaWorld'},
 {'category': 'Aquariums', 'title': 'Sea Life Sydney Aquarium'},
 {'category': 'Aquariums', 'title': 'Sea Life at Mall of America'},
 {'category': 'Archaeology', 'title': 'Alexander Mosaic'},
 {'category': 'Archaeology', 'title': 'Archaeogenetics'},
 {'category': 'Archaeology', 'title': 'Archaeological culture'},
 {'category': 'Archaeology', 'title': 'Archaeology'},
 {'category': 'Archaeology', 'title': 'Archaeometallurgy'},
 {'category': 'Archaeology', 'title': 'Assyrian continuity'},
 {'category': 'Archaeology', 'title': 'Children of Llullaillaco'},
 {'category': 'Archaeology', 'title': 'Double-headed serpent'},
 {'category': 'Archaeology', 'title': 'Enūma Eliš'},
 {'category': 'Archaeology', 'title': 'Fibula (brooch)'},
 {'category': 'Archaeology', 'title': 'Geoglyph'},
 {'category': 'Archaeology', 'title': 'Grave goods'},
 {'category': 'Archaeology', 'title': 'Historical archaeology'},
 {'category': 'Archaeology', 'title': 'Late Bronze Age collapse'},
 {'category': 'Archaeology', 'title': 'Linear Pottery culture'},
 {'category': 'Archaeology', 'title': 'Marxist archaeology'},
 {'category': 'Archaeology', 'title': 'Metal detector'},
 {'category': 'Archaeology', 'title': 'Near Eastern archaeology'},
 {'category': 'Archaeology', 'title': 'Processual archaeology'},
 {'category': 'Archaeology', 'title': 'Provenance'},
 {'category': 'Archaeology', 'title': 'Radiocarbon dating'},
 {'category': 'Archaeology', 'title': 'Sea Peoples'},
 {'category': 'Archaeology', 'title': 'Stele'},
 {'category': 'Archaeology', 'title': 'Taung Child'},
 {'category': 'Archaeology',
  'title': 'The International Association for Assyriology'},
 {'category': 'Archaeology', 'title': 'Type site'},
 {'category': 'Archaeology', 'title': 'Venus of Berekhat Ram'},
 {'category': 'Archaeology', 'title': 'Bell Beaker culture'},
 {'category': 'Archaeology',
  'title': 'National Campus for the Archaeology of Israel'},
 {'category': 'Archaeology', 'title': 'Zooarchaeology'},
 {'category': 'Architecture', 'title': 'Anglo-Saxon architecture'},
 {'category': 'Architecture', 'title': 'Architectural style'},
 {'category': 'Architecture', 'title': 'Architectural theory'},
 {'category': 'Architecture', 'title': 'Architecture'},
 {'category': 'Architecture', 'title': 'Architecture of Singapore'},
 {'category': 'Architecture', 'title': 'Bauhaus'},
 {'category': 'Architecture', 'title': 'Building code'},
 {'category': 'Architecture', 'title': 'Chinese architecture'},
 {'category': 'Architecture', 'title': 'Chinoiserie'},
 {'category': 'Architecture', 'title': 'Classical architecture'},
 {'category': 'Architecture', 'title': 'Constructivism'},
 {'category': 'Architecture', 'title': 'Contemporary architecture'},
 {'category': 'Architecture', 'title': 'Cupola'},
 {'category': 'Architecture', 'title': 'Floor plan'},
 {'category': 'Architecture', 'title': 'Humpy'},
 {'category': 'Architecture', 'title': 'Infrastructure'},
 {'category': 'Architecture', 'title': 'Interior design'},
 {'category': 'Architecture', 'title': "Jane's Walk"},
 {'category': 'Architecture', 'title': 'Landscape architecture'},
 {'category': 'Architecture', 'title': 'Landscape urbanism'},
 {'category': 'Architecture', 'title': 'Mathematics and architecture'},
 {'category': 'Architecture', 'title': 'Memorial'},
 {'category': 'Architecture', 'title': 'Monolithic architecture'},
 {'category': 'Architecture', 'title': 'Moroccan architecture'},
 {'category': 'Architecture', 'title': 'Mughal architecture'},
 {'category': 'Architecture', 'title': 'National memorial'},
 {'category': 'Architecture', 'title': 'Piano nobile'},
 {'category': 'Architecture', 'title': 'Quinta de Olivos'},
 {'category': 'Architecture', 'title': 'Scale model'},
 {'category': 'Architecture', 'title': 'Surveying'},
 {'category': 'Architecture', 'title': 'Technical drawing'},
 {'category': 'Architecture', 'title': 'The Architectural Review'},
 {'category': 'Architecture', 'title': 'Timber framing'},
 {'category': 'Architecture', 'title': 'Vastu shastra'},
 {'category': 'Architecture', 'title': 'World Architecture Festival'},
 {'category': 'Architecture', 'title': 'Architectural model'},
 {'category': 'Architecture', 'title': 'Architecture of Russia'},
 {'category': 'Architecture', 'title': 'Battlement'},
 {'category': 'Architecture', 'title': 'Châteauesque'},
 {'category': 'Architecture', 'title': 'Multiview orthographic projection'},
 {'category': 'Architecture', 'title': 'Sacral architecture'},
 {'category': 'Archives', 'title': '7-Zip'},
 {'category': 'Archives', 'title': 'Aminet'},
 {'category': 'Archives', 'title': 'ArXiv'},
 {'category': 'Archives', 'title': 'Archive.today'},
 {'category': 'Archives', 'title': 'Barbarastollen underground archive'},
 {'category': 'Archives', 'title': 'CTAN'},
 {'category': 'Archives', 'title': 'Internet Archive'},
 {'category': 'Archives', 'title': 'TVARK'},
 {'category': 'Archives', 'title': 'Web archiving'},
 {'category': 'Archives', 'title': 'WordPress'},
 {'category': 'Archosaurs', 'title': 'Albisaurus'},

In [21]:
# =========================
# 3. EXTRACT SIMPLE + EN TEXTS
# =========================

results = []

for pair in tqdm(matched_pairs, desc="Extracting texts"):
    cat = pair["category"]
    title = pair["title"]

    simple_text = get_page_extract(title, API_SIMPLE)
    en_text = get_page_extract(title, API_EN)


    results.append({
        "category": cat,
        "title": title,
        "simple_text": simple_text,
        "en_text": en_text
    })

    time.sleep(0.1)

with open("category_title_texts_disciplinary3.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"Extracted valid text pairs for {len(results)} articles.")

# =========================
# 4. CREATE PAIRWISE CSV
# =========================

output_rows = []

for entry in results:
    if entry is None or entry.get("simple_text") is None or entry.get("en_text") is None:
      continue
    simple_text = entry["simple_text"].strip()
    en_text = entry["en_text"].strip()
    category = entry["category"].strip()
    title = entry["title"].strip()

    label = random.randint(0, 1)

    if label == 1:
        sentence_1 = en_text
        sentence_2 = simple_text
    else:
        sentence_1 = simple_text
        sentence_2 = en_text

    output_rows.append({
        "sentence_1": sentence_1,
        "sentence_2": sentence_2,
        "label": label,
        "category": category,
        "title": title
    })

# Balance labels
label_0 = [row for row in output_rows if row["label"] == 0]
label_1 = [row for row in output_rows if row["label"] == 1]

min_len = min(len(label_0), len(label_1))

balanced_rows = label_0[:min_len] + label_1[:min_len]
random.shuffle(balanced_rows)

with open("output_with_disciplinary_category.csv", "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = [
        "sentence_1",
        "sentence_2",
        "label",
        "category",
        "title"
    ]

    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(balanced_rows)

print(f"Final balanced dataset size: {len(balanced_rows)}")
print("Saved: output_with_disciplinary_category.csv")

Extracting texts: 100%|██████████| 6073/6073 [5:39:23<00:00,  3.35s/it]

Extracted valid text pairs for 6073 articles.
Final balanced dataset size: 5460
Saved: output_with_disciplinary_category.csv

In [ ]:
count = 0
for i, entry in enumerate(results):
    if entry is None or entry.get("simple_text") is None:
        count += 1
print(count)

483

In [22]:
import pandas as pd

df = pd.read_csv("output_with_disciplinary_category.csv")
print(len(df))
print(df.head())

5460
                                          sentence_1  \
0  Decomposition is the process by which dead org...
1  Chlorophyta or  chlorophytes is a major divisi...
2  In logic and math, contraposition is the right...
3  This is a list of food days by country. Many c...
4  Photons  (from Greek φως, meaning light), in m...

                                          sentence_2  label     category  \
0  Decomposition, or rotting, is what happens to ...      1      Biology
1  Chlorophyta are a division of green algae.\nIt...      1        Algae
2  In logic and mathematics, contraposition, or t...      0        Logic
3  This is a list of food days by country. Many c...      1  Observances
4  A photon (from Ancient Greek  φῶς, φωτός (phôs...      0        Light

               title
0      Decomposition
1        Chlorophyta
2     Contraposition
3  List of food days
4             Photon

In [ ]:
df

,sentence_1,sentence_2,label,category,title
0,Archosauromorpha is a clade of diapsid reptile...,"Archosauromorpha (Greek for ""ruling lizard for...",0,Reptiles,Archosauromorpha
1,"Detective Conan (名探偵コナン, Meitantei Konan), als...","Case Closed, also officially known as Detectiv...",0,Manga,Case Closed
2,Consonant mutation is change in a consonant in...,Consonant mutation is a feature in languages w...,1,Linguistics,Consonant mutation
3,Xenophobia (from Ancient Greek ξένος (xénos) ...,Xenophobia is the fear or dislike of strangers...,1,Xenophobia,Xenophobia
4,"The meat ant (Iridomyrmex purpureus), also cal...","The meat ant (Iridomyrmex purpureus), also kno...",0,Ants,Meat ant
...,...,...,...,...,...
5803,The mole (symbol: mol) is the SI unit used to ...,The mole (symbol mol) is a unit of measurement...,0,Chemistry,Mole (unit)
5804,A siphon is a long tube-like structure that is...,A siphon is an anatomical structure which is p...,0,Molluscs,Siphon (mollusc)
5805,Shogun Warriors may refer to:\n\nShogun Warrio...,Shogun Warriors was a line of robot toyline re...,1,Robots,Shogun Warriors
5806,Discovery is the act of detecting something ne...,Discovery is the act of detecting something ne...,1,Cognition,Discovery (observation)
5807,"MBM is shortened from MultiBitMap which, as th...",MBM (an abbreviation of Multibitmap) is a file...,1,Graphics,MBM (file format)

In [ ]:
pip install pylatexenc

Collecting pylatexenc
  Downloading pylatexenc-2.10.tar.gz (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.6/162.6 kB 15.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pylatexenc
  Building wheel for pylatexenc (setup.py) ... done
  Created wheel for pylatexenc: filename=pylatexenc-2.10-py3-none-any.whl size=136817 sha256=865b298ce97e0d58254c26998a24cab787e6f6ab724473c354f59b4049bc73de
  Stored in directory: /root/.cache/pip/wheels/06/3e/78/fa1588c1ae991bbfd814af2bcac6cef7a178beee1939180d46
Successfully built pylatexenc
Installing collected packages: pylatexenc
Successfully installed pylatexenc-2.10

In [35]:
# ---------------------------
# Install required packages if needed
# ---------------------------
import subprocess
import sys


def install_and_import(package, import_name=None):
    """Install a missing package, then import it."""
    import_name = import_name or package

    try:
        return __import__(import_name)
    except ImportError:
        subprocess.check_call(
            [sys.executable, "-m", "pip", "install", "-q", package]
        )
        return __import__(import_name)


ftfy = install_and_import("ftfy")
install_and_import("pylatexenc")
install_and_import("beautifulsoup4", "bs4")
install_and_import("tqdm")


# ---------------------------
# Imports
# ---------------------------
import csv
import html
import re
import unicodedata

import pandas as pd
from bs4 import BeautifulSoup
from pylatexenc.latex2text import LatexNodes2Text
from tqdm.auto import tqdm


tqdm.pandas()


# ---------------------------
# Optional: Mount Google Drive
# ---------------------------
"""
from google.colab import drive

drive.mount("/content/drive")

file_path = (
    "/content/drive/MyDrive/"
    "output_with_disciplinary_category.csv"
)
"""


# ---------------------------
# 1️⃣ Load CSV safely
# ---------------------------
file_path = "output_with_disciplinary_category.csv"

try:
    df1 = pd.read_csv(file_path, encoding="utf-8")
except UnicodeDecodeError:
    df1 = pd.read_csv(file_path, encoding="latin1")

print("CSV loaded. Rows:", len(df1))


# ---------------------------
# 2️⃣ Verify required columns
# ---------------------------
required_columns = {
    "sentence_1",
    "sentence_2",
    "label",
    "category",
    "title",
}

missing_columns = required_columns.difference(df1.columns)

if missing_columns:
    raise ValueError(
        f"Missing required columns: {sorted(missing_columns)}"
    )


# ---------------------------
# 3️⃣ Preserve original content
# ---------------------------
df1["sentence_1_orig"] = df1["sentence_1"]
df1["sentence_2_orig"] = df1["sentence_2"]


# ---------------------------
# 4️⃣ Wikipedia section handling
# ---------------------------
TERMINAL_WIKIPEDIA_SECTIONS = [
    "See also",
    "Related pages",
    "Related articles",
    "References",
    "Reference",
    "Notes",
    "Footnotes",
    "Citations",
    "Sources",
    "Notes and references",
    "References and notes",
    "Notes and sources",
    "Notes and citations",
    "Bibliography",
    "Bibliographies",
    "Works cited",
    "Literature cited",
    "Further reading",
    "Further readings",
    "Suggested reading",
    "External links",
    "External link",
    "Other websites",
    "Other website",
]


WIKIPEDIA_HEADER_PATTERN = re.compile(
    r"""
    ^[ \t]*
    ={2,6}
    [ \t]*
    (.*?)
    [ \t]*
    ={2,6}
    [ \t]*
    $
    """,
    flags=re.IGNORECASE | re.MULTILINE | re.VERBOSE,
)


TERMINAL_SECTION_NAMES = {
    section.casefold()
    for section in TERMINAL_WIKIPEDIA_SECTIONS
}


def normalize_heading_name(heading):
    heading = re.sub(r"\s+", " ", heading)
    return heading.strip().casefold()


def remove_terminal_wikipedia_sections(text):
    """
    Remove the earliest terminal heading and everything after it.
    """
    if not text:
        return text, False

    for match in WIKIPEDIA_HEADER_PATTERN.finditer(text):
        heading_name = normalize_heading_name(match.group(1))

        if heading_name in TERMINAL_SECTION_NAMES:
            return text[:match.start()].rstrip(), True

    return text, False


def remove_nonterminal_wikipedia_headers(text):
    """
    Remove remaining heading lines while keeping their section content.
    """
    if not text:
        return text

    return WIKIPEDIA_HEADER_PATTERN.sub("", text)


# ---------------------------
# 5️⃣ Formula extraction and conversion
# ---------------------------
latex_converter = LatexNodes2Text(strict_latex=False)

# Formula forms commonly found in English and Simple English Wikipedia.
FORMULA_PATTERNS = [
    re.compile(r"<math\b[^>]*>.*?</math>", re.IGNORECASE | re.DOTALL),
    re.compile(r"\$\$.*?\$\$", re.DOTALL),
    re.compile(r"\\\[.*?\\\]", re.DOTALL),
    re.compile(r"\\\(.*?\\\)", re.DOTALL),
    re.compile(r"(?<!\$)\$(?!\$).*?(?<!\$)\$(?!\$)", re.DOTALL),
    re.compile(
        r"\{\{\s*(?:math|mvar|nowrap)\s*\|.*?\}\}",
        re.IGNORECASE | re.DOTALL,
    ),
]

FORMULA_TOKEN_PATTERN = re.compile(r"⟪FORMULA_(\d+)⟫")

# This detects LaTeX-like material that survived conversion.
LEFTOVER_FORMULA_PATTERN = re.compile(
    r"""
    \\(?:begin|end|frac|sqrt|text|mathrm|mathbf|mathit|
       operatorname|displaystyle|ce|left|right)\b
    |
    \\[A-Za-z]+
    |
    \$\$.*?\$\$
    |
    (?<!\$)\$(?!\$).*?(?<!\$)\$(?!\$)
    |
    \\\[.*?\\\]
    |
    \\\(.*?\\\)
    |
    <math\b
    |
    </?m(?:ath|row|i|n|o|frac|sup|sub|sqrt|text)\b
    """,
    flags=re.IGNORECASE | re.DOTALL | re.VERBOSE,
)


def extract_formulas(text):
    """
    Replace formulas with stable tokens before HTML cleanup.

    This prevents BeautifulSoup or other cleanup steps from deleting them.
    """
    formulas = []

    def save_formula(match):
        token = f"⟪FORMULA_{len(formulas)}⟫"
        formulas.append(match.group(0))
        return token

    for pattern in FORMULA_PATTERNS:
        text = pattern.sub(save_formula, text)

    return text, formulas


def convert_mathml_to_text(markup):
    """
    Convert common MathML structures into readable plain-text notation.
    """
    soup = BeautifulSoup(markup, "html.parser")

    for fraction in soup.find_all("mfrac"):
        parts = fraction.find_all(recursive=False)

        if len(parts) >= 2:
            numerator = parts[0].get_text(" ", strip=True)
            denominator = parts[1].get_text(" ", strip=True)
            fraction.replace_with(f"({numerator})/({denominator})")

    for tag_name, operator in (("msup", "^"), ("msub", "_")):
        for tag in soup.find_all(tag_name):
            parts = tag.find_all(recursive=False)

            if len(parts) >= 2:
                base = parts[0].get_text(" ", strip=True)
                value = parts[1].get_text(" ", strip=True)
                tag.replace_with(f"{base}{operator}({value})")

    for root in soup.find_all("msqrt"):
        root.replace_with(
            f"√({root.get_text(' ', strip=True)})"
        )

    return soup.get_text(" ", strip=True)


def fallback_latex_to_text(text):
    """
    Convert common LaTeX commands that may remain after pylatexenc.
    """
    replacements = {
        r"\\times\b": "×",
        r"\\cdot\b": "·",
        r"\\pm\b": "±",
        r"\\leq?\b": "≤",
        r"\\geq?\b": "≥",
        r"\\neq\b": "≠",
        r"\\approx\b": "≈",
        r"\\rightarrow\b": "→",
        r"\\to\b": "→",
        r"\\leftarrow\b": "←",
        r"\\leftrightarrow\b": "↔",
        r"\\infty\b": "∞",
        r"\\alpha\b": "α",
        r"\\beta\b": "β",
        r"\\gamma\b": "γ",
        r"\\delta\b": "δ",
        r"\\epsilon\b": "ε",
        r"\\theta\b": "θ",
        r"\\lambda\b": "λ",
        r"\\mu\b": "μ",
        r"\\pi\b": "π",
        r"\\rho\b": "ρ",
        r"\\sigma\b": "σ",
        r"\\phi\b": "φ",
        r"\\omega\b": "ω",
        r"\\sum\b": "Σ",
        r"\\prod\b": "Π",
        r"\\int\b": "∫",
    }

    for pattern, replacement in replacements.items():
        text = re.sub(pattern, replacement, text)

    previous = None

    while previous != text:
        previous = text

        text = re.sub(
            r"\\(?:text|textrm|mathrm|mathbf|mathit|operatorname)"
            r"\s*\{([^{}]*)\}",
            r"\1",
            text,
        )

        text = re.sub(
            r"\\frac\s*\{([^{}]*)\}\s*\{([^{}]*)\}",
            r"(\1)/(\2)",
            text,
        )

        text = re.sub(
            r"\\sqrt\s*\{([^{}]*)\}",
            r"√(\1)",
            text,
        )

        text = re.sub(
            r"([A-Za-z0-9)\]])\s*\^\s*\{([^{}]+)\}",
            r"\1^(\2)",
            text,
        )

        text = re.sub(
            r"([A-Za-z0-9)\]])\s*_\s*\{([^{}]+)\}",
            r"\1_(\2)",
            text,
        )

    text = text.replace(r"\left", "")
    text = text.replace(r"\right", "")
    text = text.replace(r"\,", " ")
    text = text.replace(r"\;", " ")
    text = text.replace(r"\:", " ")
    text = text.replace(r"\!", "")

    return text


def unwrap_formula(formula):
    """
    Remove formula wrappers while retaining the formula itself.
    """
    formula = formula.strip()

    if re.match(r"<math\b", formula, flags=re.IGNORECASE):
        inner = re.sub(
            r"^\s*<math\b[^>]*>|</math>\s*$",
            "",
            formula,
            flags=re.IGNORECASE | re.DOTALL,
        )

        if re.search(
            r"</?m(?:ath|row|i|n|o|frac|sup|sub|sqrt|text)\b",
            inner,
            flags=re.IGNORECASE,
        ):
            return convert_mathml_to_text(inner)

        return inner

    if formula.startswith("$$") and formula.endswith("$$"):
        return formula[2:-2]

    if formula.startswith(r"\[") and formula.endswith(r"\]"):
        return formula[2:-2]

    if formula.startswith(r"\(") and formula.endswith(r"\)"):
        return formula[2:-2]

    if formula.startswith("$") and formula.endswith("$"):
        return formula[1:-1]

    if formula.startswith("{{") and formula.endswith("}}"):
        match = re.match(
            r"^\{\{\s*[^|{}]+\|\s*(.*?)\s*\}\}$",
            formula,
            flags=re.DOTALL,
        )

        if match:
            return match.group(1)

    return formula


def convert_formula(formula):
    """
    Convert one formula to readable plain text.

    The original formula is returned if conversion cannot be completed,
    so formulas are never silently deleted.
    """
    original_formula = formula

    try:
        formula = unwrap_formula(formula)

        # Preserve the contents of MediaWiki math wrappers.
        formula = re.sub(
            r"\{\\displaystyle\s*(.*?)\}",
            r"\1",
            formula,
            flags=re.DOTALL,
        )

        formula = re.sub(
            r"\{?\\ce\s*\{(.*?)\}\}?",
            r"\1",
            formula,
            flags=re.DOTALL,
        )

        converted = latex_converter.latex_to_text(formula)
        converted = fallback_latex_to_text(converted)

        # A second pass often resolves commands exposed by the fallback.
        converted = latex_converter.latex_to_text(converted)
        converted = html.unescape(converted)
        converted = unicodedata.normalize("NFKC", converted)
        converted = re.sub(r"[ \t]+", " ", converted).strip()

        if not converted:
            return original_formula, "conversion produced empty text"

        leftover = LEFTOVER_FORMULA_PATTERN.search(converted)

        if leftover:
            return converted, (
                "formula markup remains: "
                f"{leftover.group(0).replace(chr(10), ' ')[:120]}"
            )

        return converted, ""

    except Exception as exc:
        return original_formula, (
            f"{type(exc).__name__}: {exc}"
        )


def restore_formulas(text, formulas):
    """
    Restore all formula tokens and return conversion diagnostics.
    """
    errors = []

    def restore(match):
        formula_index = int(match.group(1))

        if formula_index >= len(formulas):
            errors.append(
                f"missing formula for token {formula_index}"
            )
            return match.group(0)

        converted, error = convert_formula(
            formulas[formula_index]
        )

        if error:
            errors.append(
                f"formula {formula_index}: {error}"
            )

        return converted

    restored = FORMULA_TOKEN_PATTERN.sub(restore, text)

    remaining_tokens = FORMULA_TOKEN_PATTERN.findall(restored)

    if remaining_tokens:
        errors.append(
            f"unrestored formula tokens: {remaining_tokens}"
        )

    return restored, "; ".join(errors)


# ---------------------------
# 6️⃣ Cleaning function with diagnostics
# ---------------------------
def clean_text_with_reason(text):
    if pd.isna(text):
        return "", "original_nan", False, ""

    original = str(text)
    cleaned = ftfy.fix_text(original)

    # Protect formulas before parsing HTML or removing markup.
    cleaned, formulas = extract_formulas(cleaned)

    # Convert HTML into visible plain text.
    cleaned = BeautifulSoup(
        cleaned,
        "html.parser",
    ).get_text(separator="\n")

    # Remove the earliest terminal section and everything after it.
    cleaned, terminal_section_removed = (
        remove_terminal_wikipedia_sections(cleaned)
    )

    # Remove non-terminal heading lines only.
    cleaned = remove_nonterminal_wikipedia_headers(cleaned)

    # Restore and convert every extracted formula.
    cleaned, formula_error = restore_formulas(
        cleaned,
        formulas,
    )

    # Try converting any unwrapped LaTeX still present in the prose.
    try:
        cleaned = latex_converter.latex_to_text(cleaned)
        cleaned = fallback_latex_to_text(cleaned)
    except Exception as exc:
        extra_error = (
            f"whole-text conversion: {type(exc).__name__}: {exc}"
        )
        formula_error = (
            f"{formula_error}; {extra_error}"
            if formula_error
            else extra_error
        )

    cleaned = html.unescape(cleaned)
    cleaned = unicodedata.normalize("NFKC", cleaned)

    for character in [
        "\u200b",
        "\u200c",
        "\u200d",
        "\u2060",
        "\u2061",
        "\ufeff",
    ]:
        cleaned = cleaned.replace(character, "")

    cleaned = re.sub(r"[ \t]+", " ", cleaned)
    cleaned = re.sub(r" *\n *", "\n", cleaned)
    cleaned = re.sub(r"\n{2,}", "\n", cleaned)
    cleaned = cleaned.strip()

    leftover_match = LEFTOVER_FORMULA_PATTERN.search(cleaned)

    if leftover_match:
        leftover_error = (
            "unconverted formula markup: "
            f"{leftover_match.group(0).replace(chr(10), ' ')[:120]}"
        )
        formula_error = (
            f"{formula_error}; {leftover_error}"
            if formula_error
            else leftover_error
        )

    formula_failed = bool(formula_error)

    if original.strip() and not cleaned:
        reason = "content_removed_by_cleaning"
    elif formula_failed:
        reason = "formula_conversion_warning"
    elif terminal_section_removed:
        reason = "terminal_section_removed"
    else:
        reason = ""

    return cleaned, reason, formula_failed, formula_error


# ---------------------------
# 7️⃣ Apply cleaning with progress bars
# ---------------------------
def clean_column(column_name):
    tqdm.pandas(
        desc=f"Cleaning {column_name}",
        unit="row",
    )

    results = df1[column_name].progress_apply(
        clean_text_with_reason
    )

    return pd.DataFrame(
        results.tolist(),
        index=df1.index,
        columns=[
            f"{column_name}_clean",
            f"{column_name}_reason",
            f"{column_name}_formula_failed",
            f"{column_name}_formula_error",
        ],
    )


sentence_1_results = clean_column("sentence_1")
sentence_2_results = clean_column("sentence_2")

df1 = pd.concat(
    [
        df1,
        sentence_1_results,
        sentence_2_results,
    ],
    axis=1,
)


# ---------------------------
# 8️⃣ Convert destroyed content to NaN
# ---------------------------
for column in ["sentence_1", "sentence_2"]:
    clean_column_name = f"{column}_clean"
    reason_column = f"{column}_reason"

    destroyed_mask = (
        df1[reason_column] == "content_removed_by_cleaning"
    )

    df1.loc[destroyed_mask, clean_column_name] = pd.NA


# ---------------------------
# 9️⃣ Save formula warnings for inspection
# ---------------------------
formula_warning_mask = (
    df1["sentence_1_formula_failed"]
    | df1["sentence_2_formula_failed"]
)

formula_warnings = df1.loc[
    formula_warning_mask,
    [
        "title",
        "sentence_1_orig",
        "sentence_1_clean",
        "sentence_1_formula_error",
        "sentence_2_orig",
        "sentence_2_clean",
        "sentence_2_formula_error",
    ],
].copy()

formula_warning_output_path = "formula_conversion_warnings.csv"

formula_warnings.to_csv(
    formula_warning_output_path,
    index=False,
    encoding="utf-8",
    quoting=csv.QUOTE_MINIMAL,
)

print(
    f"\nFormula warning report saved to: "
    f"{formula_warning_output_path} "
    f"({len(formula_warnings)} rows)"
)


# ---------------------------
# 🔟 Report cleaning results
# ---------------------------
for column in ["sentence_1", "sentence_2"]:
    reason_column = f"{column}_reason"
    formula_failed_column = f"{column}_formula_failed"

    destroyed_count = (
        df1[reason_column] == "content_removed_by_cleaning"
    ).sum()

    terminal_count = (
        df1[reason_column] == "terminal_section_removed"
    ).sum()

    formula_warning_count = (
        df1[formula_failed_column].sum()
    )

    print(f"\nResults for {column}:")
    print(f"  Content completely removed: {destroyed_count}")
    print(f"  Terminal sections removed: {terminal_count}")
    print(f"  Formula conversion warnings: {formula_warning_count}")


# ---------------------------
# 1️⃣1️⃣ Remove unusable rows
# ---------------------------
rows_before_drop = len(df1)

df1 = df1.dropna(
    subset=[
        "sentence_1_clean",
        "sentence_2_clean",
    ]
)

nonempty_mask = (
    df1["sentence_1_clean"].str.strip().ne("")
    &
    df1["sentence_2_clean"].str.strip().ne("")
)

df1 = (
    df1.loc[nonempty_mask]
    .copy()
    .reset_index(drop=True)
)

removed_rows = rows_before_drop - len(df1)

print(f"\nRemoved unusable rows: {removed_rows}")
print(f"Remaining rows: {len(df1)}")


# ---------------------------
# 1️⃣2️⃣ Replace original sentences
# ---------------------------
df1["sentence_1"] = df1["sentence_1_clean"]
df1["sentence_2"] = df1["sentence_2_clean"]

df1 = df1[
    [
        "sentence_1",
        "sentence_2",
        "label",
        "category",
        "title",
    ]
]


# ---------------------------
# 1️⃣3️⃣ Save cleaned dataframe
# ---------------------------
output_path = "output_cleaned_title.csv"

df1.to_csv(
    output_path,
    index=False,
    encoding="utf-8",
    quoting=csv.QUOTE_MINIMAL,
)

print(f"\nCleaned CSV saved to: {output_path}")

WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']

CSV loaded. Rows: 5460

Cleaning sentence_1:   0%|          | 0/5460 [00:00<?, ?row/s]

WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!
WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!

Cleaning sentence_2:   0%|          | 0/5460 [00:00<?, ?row/s]

WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!
WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!
WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!
WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!
WARNING:pylatexenc.latex2text:WARNING: Error in configuration: macro '\frac' failed its substitution!

Formula warning report saved to: formula_conversion_warnings.csv (3 rows)

Results for sentence_1:
  Content completely removed: 0
  Terminal sections removed: 4762
  Formula conversion warnings: 1

Results for sentence_2:
  Content completely removed: 0
  Terminal sections removed: 4749
  Formula conversion warnings: 2

Removed unusable rows: 0
Remaining rows: 5460

Cleaned CSV saved to: output_cleaned_title.csv

In [36]:
df1

,sentence_1,sentence_2,label,category,title
0,Decomposition is the process by which dead org...,"Decomposition, or rotting, is what happens to ...",1,Biology,Decomposition
1,Chlorophyta or chlorophytes is a major divisio...,Chlorophyta are a division of green algae.\nIt...,1,Algae,Chlorophyta
2,"In logic and math, contraposition is the right...","In logic and mathematics, contraposition, or t...",0,Logic,Contraposition
3,This is a list of food days by country. Many c...,This is a list of food days by country. Many c...,1,Observances,List of food days
4,"Photons (from Greek φως, meaning light), in ma...","A photon (from Ancient Greek φῶς, φωτός (phôs,...",0,Light,Photon
...,...,...,...,...,...
5455,Gapo is a Vietnamese social networking service...,Gapo is a social networking platform which is ...,1,Software,Gapo
5456,Horticulture is the practical botany of garden...,Horticulture (from Latin: horti + culture) is ...,0,Gardening,Horticulture
5457,Spaceflight is when an object (or spacecraft) ...,Spaceflight (also space flight) is an applicat...,0,Spaceflight,Spaceflight
5458,"A sexual fantasy is a mental image, or a patte...","A sexual fantasy, or erotic fantasy, is an aut...",0,Literature,Sexual fantasy
5459,Letharia vulpina is a lichen. People call it w...,"Letharia vulpina, commonly known as the wolf l...",0,Fungi,Letharia vulpina

In [ ]:
from google.colab import files
files.download('output_cleaned_title.csv')

In [37]:
import pandas as pd

df = pd.read_csv("output_cleaned_title.csv")
print(len(df))
print(df.head())

5460
                                          sentence_1  \
0  Decomposition is the process by which dead org...
1  Chlorophyta or chlorophytes is a major divisio...
2  In logic and math, contraposition is the right...
3  This is a list of food days by country. Many c...
4  Photons (from Greek φως, meaning light), in ma...

                                          sentence_2  label     category  \
0  Decomposition, or rotting, is what happens to ...      1      Biology
1  Chlorophyta are a division of green algae.\nIt...      1        Algae
2  In logic and mathematics, contraposition, or t...      0        Logic
3  This is a list of food days by country. Many c...      1  Observances
4  A photon (from Ancient Greek φῶς, φωτός (phôs,...      0        Light

               title
0      Decomposition
1        Chlorophyta
2     Contraposition
3  List of food days
4             Photon

In [1]:
from google.colab import drive
drive.mount('/content/drive')
import pandas as pd

with open('/content/drive/MyDrive/data/output_cleaned_title.csv', 'r') as f:
    df = pd.read_csv(f)



print("number of label 0 rows :", (df['label'] == 0).sum())
print("number of label 1 rows :", (df['label'] == 1).sum())

Mounted at /content/drive
number of label 0 rows : 2730
number of label 1 rows : 2730