In [ ]:
import requests
import time
import json
import re
import random
from tqdm import tqdm
from google.colab import files

HEADERS = {
    "User-Agent": "MyColabBot/2.0 (inesgoddi@gmail.com)"
}

SESSION = requests.Session()
SESSION.headers.update(HEADERS)

API_SIMPLE = "https://simple.wikipedia.org/w/api.php"
API_EN = "https://en.wikipedia.org/w/api.php"

REQUEST_DELAY = 1.0
MAX_RETRIES = 8

DISCIPLINARY_ROOTS = [
    # Natural sciences
    "Physics", "Chemistry", "Biology", "Astronomy", "Earth science",

    # Formal sciences
    "Mathematics", "Computer science", "Statistics", "Logic",

    # Life sciences
    "Genetics", "Neuroscience", "Ecology", "Microbiology",
    "Zoology", "Botany",

    # Medical sciences
    "Medicine", "Surgery", "Pharmacology", "Epidemiology", "Public health",

    # Engineering
    "Engineering", "Mechanical engineering", "Electrical engineering",
    "Civil engineering", "Chemical engineering", "Aerospace engineering",

    # Social sciences
    "Economics", "Psychology", "Sociology", "Political science",
    "Anthropology", "Human geography",

    # Humanities
    "Philosophy", "History", "Literature", "Linguistics", "Theology",

    # Arts
    "Arts", "Music", "Visual arts", "Performing arts",
    "Film studies", "Architecture",

    # Interdisciplinary
    "Cognitive science", "Environmental science",
    "Data science", "Artificial intelligence", "Systems science"
]

BAD_CATEGORY_PATTERNS = [
    r"^Articles? ", r"^All articles?", r"^Wikipedia ", r"^Pages?",
    r"^CS1 ", r"^Harv ", r"^Use ", r"^Redirects?",
    r"^Disambiguation", r".*errors?$", r".*cleanup.*",
    r".*needing.*", r".*lacking.*", r".*unsourced.*",
    r".*unreferenced.*", r".*broken.*", r".*template.*",
    r".*infobox.*", r".*Wikidata.*", r".*stub.*",
    r".*stubs.*", r".*citation.*", r".*coordinates.*",
    r".*authority control.*", r".*public domain.*",
    r".*incorporating.*", r".*semi-protected.*",
    r".*plot summary.*", r".*bare URLs.*",
    r".*subscription.*", r".*maintenance.*",
    r".*hidden categor.*"
]

BAD_EXACT_CATEGORIES = {
    "Contents", "Lists", "Outlines", "Reference",
    "Comparisons", "Concepts", "Entities",
    "Objects", "Data", "Information"
}

BAD_CATEGORY_REGEX = [re.compile(p, re.IGNORECASE) for p in BAD_CATEGORY_PATTERNS]

DIGIT_PATTERN = re.compile(r"\d")
NON_ALPHA_PATTERN = re.compile(r"[^a-zA-Z\- ]")

BAD_WORDS = {
    "abuse", "abusive", "violence", "violent", "rape", "murder",
    "death", "torture", "prostitution", "porn",
    "sexual", "sex", "cannibal", "cannibalism", "drug",
    "addiction", "gambling", "terrorism", "crime", "criminal",
    "childhood", "children"
}

PEOPLE_PATTERN = re.compile(
    r"\b(bankers?|lawyers?|politicians?|actors?|singers?|players?|"
    r"scientists?|philosophers?|historians?|mathematicians?|"
    r"writers?|authors?|artists?|athletes?|accountants?)\b",
    re.IGNORECASE
)

IST_PATTERN = re.compile(r"\b\w+ist(s)?\b", re.IGNORECASE)
NAME_PATTERN = re.compile(r"^[A-Z][a-z]+ [A-Z][a-z]+$")


def is_disciplinary_category(cat):
    cat = cat.strip()
    cat_lower = cat.lower()

    if cat in BAD_EXACT_CATEGORIES:
        return False

    if any(p.search(cat) for p in BAD_CATEGORY_REGEX):
        return False

    if DIGIT_PATTERN.search(cat):
        return False

    if NON_ALPHA_PATTERN.search(cat):
        return False

    if any(word in cat_lower for word in BAD_WORDS):
        return False

    if PEOPLE_PATTERN.search(cat):
        return False

    if IST_PATTERN.search(cat):
        return False

    if NAME_PATTERN.match(cat):
        return False

    if len(cat.split()) > 1:
        return False
    # strict single-word (letters only, no spaces, no hyphens)
    if not re.fullmatch(r"[A-Za-z]+", cat):
      return False

    return True


def safe_get(api_url, params, max_retries=MAX_RETRIES):
    for attempt in range(max_retries):
        try:
            response = SESSION.get(api_url, params=params, timeout=30)

            if response.status_code == 429:
                retry_after = response.headers.get("Retry-After")

                if retry_after:
                    wait = int(retry_after)
                else:
                    wait = min(90, 5 * (2 ** attempt))

                wait += random.uniform(0, 2)
                print(f"429 rate limit. Waiting {wait:.1f}s...")
                time.sleep(wait)
                continue

            response.raise_for_status()

            time.sleep(REQUEST_DELAY + random.uniform(0, 0.5))
            return response.json()

        except requests.exceptions.RequestException as e:
            wait = min(90, 3 * (2 ** attempt)) + random.uniform(0, 2)
            print(f"Request failed: {e}. Waiting {wait:.1f}s...")
            time.sleep(wait)

    return {}


def get_subcategories(category, api_url, depth=5):
    seen = set()
    to_visit = [(category, 0)]
    results = set()

    while to_visit:
        current_cat, current_depth = to_visit.pop()

        if current_cat in seen or current_depth > depth:
            continue

        seen.add(current_cat)
        cmcontinue = None

        while True:
            params = {
                "action": "query",
                "format": "json",
                "list": "categorymembers",
                "cmtitle": f"Category:{current_cat}",
                "cmnamespace": 14,
                "cmlimit": 500
            }

            if cmcontinue:
                params["cmcontinue"] = cmcontinue

            data = safe_get(api_url, params)

            subcats = [
                item["title"].replace("Category:", "")
                for item in data.get("query", {}).get("categorymembers", [])
            ]

            for subcat in subcats:
                if is_disciplinary_category(subcat):
                    results.add(subcat)

                    if current_depth < depth:
                        to_visit.append((subcat, current_depth + 1))

            cmcontinue = data.get("continue", {}).get("cmcontinue")

            if not cmcontinue:
                break

    return results


def fetch_root_subcats(cat):
    print(f"\nProcessing root category: {cat}")

    simple = get_subcategories(cat, API_SIMPLE, depth=7)
    en = get_subcategories(cat, API_EN, depth=7)

    return simple, en


print("Using predefined disciplinary root categories...")

subcategories_simple = set()
subcategories_en = set()

for cat in tqdm(DISCIPLINARY_ROOTS, desc="Getting subcategories"):
    simple, en = fetch_root_subcats(cat)
    subcategories_simple.update(simple)
    subcategories_en.update(en)

common_cats = sorted(
    (subcategories_simple & subcategories_en) | set(DISCIPLINARY_ROOTS)
)

common_cats = [
    cat for cat in common_cats
    if is_disciplinary_category(cat)
]

print(f"\nKept {len(common_cats)} disciplinary categories.")

with open("disciplinary_categories3.json", "w", encoding="utf-8") as f:
    json.dump(common_cats, f, ensure_ascii=False, indent=2)

files.download("disciplinary_categories3.json")

Using predefined disciplinary root categories...

Getting subcategories:   0%|          | 0/48 [00:00<?, ?it/s]

Processing root category: Physics

Getting subcategories:   2%|▏         | 1/48 [02:18<1:48:28, 138.47s/it]

Processing root category: Chemistry

Getting subcategories:   4%|▍         | 2/48 [02:58<1:01:34, 80.32s/it]

Processing root category: Biology

Getting subcategories:   6%|▋         | 3/48 [14:15<4:24:39, 352.88s/it]

Processing root category: Astronomy

Getting subcategories:   8%|▊         | 4/48 [15:35<2:59:53, 245.31s/it]

Processing root category: Earth science

Getting subcategories:  10%|█         | 5/48 [15:38<1:53:10, 157.92s/it]

Processing root category: Mathematics

Getting subcategories:  12%|█▎        | 6/48 [16:10<1:20:29, 115.00s/it]

Processing root category: Computer science

Getting subcategories:  15%|█▍        | 7/48 [16:49<1:01:35, 90.14s/it]

Processing root category: Statistics

Getting subcategories:  17%|█▋        | 8/48 [16:57<42:40, 64.02s/it]

Processing root category: Logic

Getting subcategories:  19%|█▉        | 9/48 [17:20<33:15, 51.18s/it]

Processing root category: Genetics

Getting subcategories:  21%|██        | 10/48 [18:14<33:05, 52.24s/it]

Processing root category: Neuroscience

Getting subcategories:  23%|██▎       | 11/48 [24:33<1:33:45, 152.04s/it]

Processing root category: Ecology

Getting subcategories:  25%|██▌       | 12/48 [26:26<1:24:12, 140.34s/it]

Processing root category: Microbiology

Getting subcategories:  27%|██▋       | 13/48 [28:52<1:22:42, 141.79s/it]

Processing root category: Zoology

Getting subcategories:  29%|██▉       | 14/48 [43:27<3:25:56, 363.42s/it]

Processing root category: Botany

Getting subcategories:  31%|███▏      | 15/48 [45:55<2:44:11, 298.52s/it]

Processing root category: Medicine

Getting subcategories:  33%|███▎      | 16/48 [46:12<1:53:55, 213.61s/it]

Processing root category: Surgery

Getting subcategories:  35%|███▌      | 17/48 [46:41<1:21:43, 158.18s/it]

Processing root category: Pharmacology

Getting subcategories:  38%|███▊      | 18/48 [47:04<58:46, 117.55s/it]

Processing root category: Epidemiology

Getting subcategories:  40%|███▉      | 19/48 [47:10<40:35, 83.99s/it]

Processing root category: Public health

Getting subcategories:  42%|████▏     | 20/48 [52:36<1:13:05, 156.64s/it]

Processing root category: Engineering

Getting subcategories:  44%|████▍     | 21/48 [52:43<50:16, 111.73s/it]

Processing root category: Mechanical engineering

Getting subcategories:  46%|████▌     | 22/48 [59:08<1:24:00, 193.87s/it]

Processing root category: Electrical engineering

Getting subcategories:  48%|████▊     | 23/48 [59:11<56:55, 136.62s/it]

Processing root category: Civil engineering

Getting subcategories:  50%|█████     | 24/48 [1:01:58<58:13, 145.57s/it]

Processing root category: Chemical engineering

Getting subcategories:  52%|█████▏    | 25/48 [1:02:04<39:44, 103.67s/it]

Processing root category: Aerospace engineering

Getting subcategories:  54%|█████▍    | 26/48 [1:02:58<32:35, 88.91s/it]

Processing root category: Economics

Getting subcategories:  56%|█████▋    | 27/48 [1:05:54<40:18, 115.17s/it]

Processing root category: Psychology

Getting subcategories:  58%|█████▊    | 28/48 [1:10:18<53:11, 159.57s/it]

Processing root category: Sociology

Getting subcategories:  60%|██████    | 29/48 [1:11:19<41:11, 130.10s/it]

Processing root category: Political science

Getting subcategories:  62%|██████▎   | 30/48 [1:11:26<27:58, 93.24s/it]

Processing root category: Anthropology

Getting subcategories:  65%|██████▍   | 31/48 [1:28:48<1:47:00, 377.69s/it]

Processing root category: Human geography

Getting subcategories:  67%|██████▋   | 32/48 [1:29:33<1:14:10, 278.13s/it]

Processing root category: Philosophy

Getting subcategories:  69%|██████▉   | 33/48 [1:29:55<50:17, 201.19s/it]

Processing root category: History

Getting subcategories:  71%|███████   | 34/48 [1:34:55<53:53, 230.95s/it]

Processing root category: Literature

Getting subcategories:  73%|███████▎  | 35/48 [1:35:51<38:38, 178.38s/it]

Processing root category: Linguistics

Getting subcategories:  75%|███████▌  | 36/48 [1:38:15<33:37, 168.10s/it]

Processing root category: Theology

Getting subcategories:  77%|███████▋  | 37/48 [1:40:23<28:35, 155.96s/it]

Processing root category: Arts

Getting subcategories:  79%|███████▉  | 38/48 [1:40:26<18:20, 110.05s/it]

Processing root category: Music

Getting subcategories:  81%|████████▏ | 39/48 [1:40:35<11:58, 79.88s/it]

Processing root category: Visual arts

Getting subcategories:  83%|████████▎ | 40/48 [1:42:55<13:01, 97.70s/it]

Processing root category: Performing arts

Getting subcategories:  85%|████████▌ | 41/48 [1:57:22<38:19, 328.55s/it]

Processing root category: Film studies

Getting subcategories:  88%|████████▊ | 42/48 [1:57:25<23:04, 230.82s/it]

Processing root category: Architecture

Getting subcategories:  90%|████████▉ | 43/48 [1:59:18<16:17, 195.50s/it]

Processing root category: Cognitive science

Getting subcategories:  92%|█████████▏| 44/48 [2:10:03<22:02, 330.58s/it]

Processing root category: Environmental science

Getting subcategories:  94%|█████████▍| 45/48 [2:11:36<12:57, 259.32s/it]

Processing root category: Data science

Getting subcategories:  96%|█████████▌| 46/48 [2:11:40<06:05, 182.50s/it]

Processing root category: Artificial intelligence

Getting subcategories:  98%|█████████▊| 47/48 [2:11:45<02:09, 129.25s/it]

Processing root category: Systems science

Getting subcategories: 100%|██████████| 48/48 [2:11:57<00:00, 164.95s/it]

Kept 267 disciplinary categories.

In [ ]:
from numpy import char
import requests
import time
import json
import random
import csv
import re
from tqdm import tqdm
import pandas as pd
from google.colab import files

HEADERS = {
    "User-Agent": "MyColabBot/1.0 (inesgoddi@gmail.com)"
}

API_SIMPLE = "https://simple.wikipedia.org/w/api.php"
API_EN = "https://en.wikipedia.org/w/api.php"

DISCIPLINARY_ROOTS = [
    "Science", "Natural sciences",
    "Physics", "Theoretical physics", "Applied physics", "Quantum mechanics",
    "Astrophysics", "Astronomy", "Cosmology", "Particle physics",
    "Biology", "Molecular biology", "Cell biology", "Genetics",
    "Evolutionary biology", "Ecology", "Neuroscience",
    "Microbiology", "Zoology", "Botany",
    "Chemistry", "Organic chemistry", "Inorganic chemistry",
    "Physical chemistry", "Biochemistry", "Analytical chemistry",
    "Earth sciences", "Geology", "Geophysics", "Meteorology",
    "Oceanography", "Environmental science", "Climate science",

    "Mathematics", "Pure mathematics", "Applied mathematics",
    "Algebra", "Geometry", "Topology", "Number theory",
    "Combinatorics", "Mathematical analysis",
    "Statistics", "Probability theory",
    "Logic", "Mathematical logic",
    "Theoretical computer science",

    "Computer science", "Artificial intelligence",
    "Machine learning", "Deep learning",
    "Data science", "Information theory",
    "Information systems", "Software engineering",
    "Computer engineering", "Human–computer interaction",
    "Computer vision", "Natural language processing",
    "Cybersecurity", "Distributed computing",

    "Engineering", "Electrical engineering", "Mechanical engineering",
    "Civil engineering", "Chemical engineering",
    "Aerospace engineering", "Biomedical engineering",
    "Industrial engineering", "Systems engineering",
    "Materials science", "Nanotechnology",

    "Medicine", "Public health", "Epidemiology",
    "Pathology", "Pharmacology", "Immunology",
    "Anatomy", "Physiology",
    "Clinical medicine", "Surgery",
    "Psychiatry", "Nursing", "Dentistry",

    "Social sciences",
    "Economics", "Microeconomics", "Macroeconomics",
    "Political science", "Public policy", "International relations",
    "Sociology", "Social theory",
    "Anthropology", "Cultural anthropology",
    "Human geography", "Economic geography",
    "Demography", "Criminology",
    "Psychology", "Cognitive psychology",
    "Developmental psychology", "Social psychology",
    "Behavioral science",

    "Humanities",
    "Philosophy", "Epistemology", "Metaphysics",
    "Ethics", "Logic (philosophy)", "Philosophy of science",
    "History", "Historiography",
    "Archaeology",
    "Linguistics", "Phonetics", "Syntax", "Semantics",
    "Literary theory", "Literature",
    "Religious studies", "Theology",
    "Classics",

    "Law", "Criminal law", "Civil law",
    "International law", "Constitutional law",
    "Legal theory",

    "Business", "Management", "Organizational behavior",
    "Finance", "Accounting", "Marketing",
    "Operations management",
    "Entrepreneurship",

    "Education", "Pedagogy", "Educational psychology",
    "Curriculum studies", "Instructional design",

    "Cognitive science", "Data analysis",
    "Systems science", "Complex systems",
    "Environmental studies",
    "Sustainability", "Urban studies",
    "Science and technology studies",

    "Communication", "Media studies",
    "Journalism", "Rhetoric",
    "Library science", "Information science",

    "Arts", "Musicology", "Art history",
    "Visual arts", "Performing arts"
]

BAD_CATEGORY_PATTERNS = [
    r"^Articles? ",
    r"^All articles?",
    r"^Wikipedia ",
    r"^Pages? ",
    r"^CS1 ",
    r"^Harv ",
    r"^Use ",
    r"^Redirects? ",
    r"^Disambiguation",
    r".*errors?$",
    r".*cleanup.*",
    r".*needing.*",
    r".*lacking.*",
    r".*unsourced.*",
    r".*unreferenced.*",
    r".*broken.*",
    r".*template.*",
    r".*infobox.*",
    r".*Wikidata.*",
    r".*stub.*",
    r".*stubs.*",
    r".*citation.*",
    r".*coordinates.*",
    r".*authority control.*",
    r".*public domain.*",
    r".*incorporating.*",
    r".*semi-protected.*",
    r".*plot summary.*",
    r".*bare URLs.*",
    r".*subscription.*",
    r".*maintenance.*",
    r".*hidden categor.*"
]

BAD_EXACT_CATEGORIES = {
    "Contents",
    "Lists",
    "Outlines",
    "Reference",
    "Comparisons",
    "Concepts",
    "Entities",
    "Objects",
    "Data",
    "Information"
}



# =========================
# EXTRA FILTERING (NEW)
# =========================

# Compile regex once (faster)
BAD_CATEGORY_REGEX = [re.compile(p, re.IGNORECASE) for p in BAD_CATEGORY_PATTERNS]

DIGIT_PATTERN = re.compile(r"\d")
NON_ALPHA_PATTERN = re.compile(r"[^a-zA-Z\- ]")

BAD_WORDS = {
    "abuse", "abusive", "violence", "violent", "rape", "murder",
    "death", "suicide", "torture", "prostitution", "porn",
    "sexual", "sex", "cannibal", "cannibalism", "drug",
    "addiction", "gambling", "terrorism", "crime", "criminal"
}

PEOPLE_PATTERN = re.compile(
    r"\b(bankers?|lawyers?|politicians?|actors?|singers?|players?|"
    r"scientists?|philosophers?|historians?|mathematicians?)\b",
    re.IGNORECASE
)

IST_PATTERN = re.compile(r"\b\w+ist(s)?\b", re.IGNORECASE)

# Detect likely person names (Firstname Lastname)
NAME_PATTERN = re.compile(r"^[A-Z][a-z]+ [A-Z][a-z]+$")


def is_disciplinary_category(cat):
    cat = cat.strip()
    cat_lower = cat.lower()

    # 1. Exact blacklist
    if cat in BAD_EXACT_CATEGORIES:
        return False

    # 2. Pattern blacklist (Wikipedia junk)
    if any(p.search(cat) for p in BAD_CATEGORY_REGEX):
        return False

    # 3. ❌ Remove digits
    if DIGIT_PATTERN.search(cat):
        return False

    # 4. ❌ Remove weird symbols (optional but strong)
    if NON_ALPHA_PATTERN.search(cat):
        return False

    # 5. ❌ Remove bad semantic words
    if any(word in cat_lower for word in BAD_WORDS):
        return False

    # 6. ❌ Remove professions / social groups
    if PEOPLE_PATTERN.search(cat):
        return False

    # 7. ❌ Remove "-ist" words (bias / ideology)
    if IST_PATTERN.search(cat):
        return False

    # 8. ❌ Remove likely person names
    if NAME_PATTERN.match(cat):
        return False

    if len(cat.split()) > 3:
      return False

    return True

def safe_get(api_url, params, max_retries=3):
    for attempt in range(max_retries):
        try:
            r = requests.get(api_url, headers=HEADERS, params=params, timeout=30)
            r.raise_for_status()
            return r.json()
        except Exception as e:
            print(f"Request failed: {e}. Retry {attempt + 1}/{max_retries}")
            time.sleep(1)

    return {}

def get_subcategories(category, api_url, depth=5):
    seen = set()
    to_visit = [(category, 0)]
    results = set()

    while to_visit:
        current_cat, current_depth = to_visit.pop()

        if current_cat in seen or current_depth > depth:
            continue

        seen.add(current_cat)
        cmcontinue = None

        while True:
            params = {
                "action": "query",
                "format": "json",
                "list": "categorymembers",
                "cmtitle": f"Category:{current_cat}",
                "cmnamespace": 14,
                "cmlimit": "max"
            }

            if cmcontinue:
                params["cmcontinue"] = cmcontinue

            data = safe_get(api_url, params)

            subcats = [
                item["title"].replace("Category:", "")
                for item in data.get("query", {}).get("categorymembers", [])
            ]

            for subcat in subcats:
                if is_disciplinary_category(subcat):
                    results.add(subcat)
                    to_visit.append((subcat, current_depth + 1))

            cmcontinue = data.get("continue", {}).get("cmcontinue")
            if not cmcontinue:
                break

            time.sleep(0.1)

    return results

def get_category_articles(category, api_url, limit=100):
    titles = []
    cmcontinue = None

    while len(titles) < limit:
        params = {
            "action": "query",
            "format": "json",
            "list": "categorymembers",
            "cmtitle": f"Category:{category}",
            "cmnamespace": 0,
            "cmlimit": "max"
        }

        if cmcontinue:
            params["cmcontinue"] = cmcontinue

        data = safe_get(api_url, params)

        titles.extend([
            page["title"]
            for page in data.get("query", {}).get("categorymembers", [])
        ])

        cmcontinue = data.get("continue", {}).get("cmcontinue")
        if not cmcontinue:
            break

        time.sleep(0.1)

    return titles[:limit]

def filter_existing_titles_in_en(titles):
    existing = []
    batch_size = 50

    for i in range(0, len(titles), batch_size):
        batch = titles[i:i + batch_size]

        params = {
            "action": "query",
            "format": "json",
            "titles": "|".join(batch),
            "redirects": 1
        }

        data = safe_get(API_EN, params)

        for page in data.get("query", {}).get("pages", {}).values():
            if "missing" not in page:
                existing.append(page["title"])

        time.sleep(0.1)

    return existing

def get_page_extract(title, api_url):
    params = {
        "action": "query",
        "format": "json",
        "prop": "extracts",
        "explaintext": True,
        "titles": title,
        "redirects": 1
    }

    data = safe_get(api_url, params)

    pages = data.get("query", {}).get("pages", {})

    for page in pages.values():
        if "missing" in page:
            return None
        return page.get("extract", "")

    return None

def is_valid_text(text, min_words=100):
    if not text:
        return False

    words = text.split()

    if len(words) < min_words:
        return False

    return True
'''
# =========================
# 1. GET DISCIPLINARY CATEGORIES
# =========================

print("Using predefined disciplinary root categories...")

subcategories_simple = set()
subcategories_en = set()

for cat in tqdm(DISCIPLINARY_ROOTS, desc="Getting subcategories"):
    subcategories_simple.update(get_subcategories(cat, API_SIMPLE, depth=2))
    subcategories_en.update(get_subcategories(cat, API_EN, depth=2))

common_cats = sorted(
    (subcategories_simple & subcategories_en) | set(DISCIPLINARY_ROOTS)
)

common_cats = [
    cat for cat in common_cats
    if is_disciplinary_category(cat)
]

print(f"Kept {len(common_cats)} disciplinary categories.")

with open("disciplinary_categories2.json", "w", encoding="utf-8") as f:
    json.dump(common_cats, f, ensure_ascii=False, indent=2)

files.download("disciplinary_categories2.json")


# =========================
# 2. COLLECT ARTICLE TITLES
# =========================

matched_pairs = []

MAX_TOTAL_PAIRS = 10000
MAX_ARTICLES_PER_CATEGORY = 100

for cat in tqdm(common_cats, desc="Collecting articles"):
    if len(cat.split()) >1 or any(char.isdigit() for char in cat):
        continue

    print(f"Collecting articles for category: {cat}")
    titles_simple = get_category_articles(
        cat,
        API_SIMPLE,
        limit=MAX_ARTICLES_PER_CATEGORY * 2
    )

    if not titles_simple:
        continue

    existing_in_en = filter_existing_titles_in_en(titles_simple)

    count_for_cat = 0

    for title in existing_in_en:
        matched_pairs.append({
            "category": cat,
            "title": title
        })

        count_for_cat += 1

        if count_for_cat >= MAX_ARTICLES_PER_CATEGORY:
            break

        if len(matched_pairs) >= MAX_TOTAL_PAIRS:
            break

    if len(matched_pairs) >= MAX_TOTAL_PAIRS:
        break

with open("category_title_pairs_disciplinary.json", "w", encoding="utf-8") as f:
    json.dump(matched_pairs, f, ensure_ascii=False, indent=2)

print(f"Collected {len(matched_pairs)} category-title pairs.")
print(matched_pairs)
'''
# =========================
# 3. EXTRACT SIMPLE + EN TEXTS
# =========================
'''
results = []

for pair in tqdm(matched_pairs, desc="Extracting texts"):
    cat = pair["category"]
    title = pair["title"]

    simple_text = get_page_extract(title, API_SIMPLE)
    en_text = get_page_extract(title, API_EN)

    if not is_valid_text(simple_text, min_words=100):
        continue

    if not is_valid_text(en_text, min_words=100):
        continue

    results.append({
        "category": cat,
        "title": title,
        "simple_text": simple_text,
        "en_text": en_text
    })

    time.sleep(0.1)

with open("category_title_texts_disciplinary.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"Extracted valid text pairs for {len(results)} articles.")

# =========================
# 4. CREATE PAIRWISE CSV
# =========================

output_rows = []

for entry in results:
    simple_text = entry["simple_text"].strip()
    en_text = entry["en_text"].strip()
    category = entry["category"].strip()
    title = entry["title"].strip()

    label = random.randint(0, 1)

    if label == 1:
        sentence_1 = en_text
        sentence_2 = simple_text
    else:
        sentence_1 = simple_text
        sentence_2 = en_text

    output_rows.append({
        "sentence_1": sentence_1,
        "sentence_2": sentence_2,
        "label": label,
        "category": category,
        "title": title
    })

# Balance labels
label_0 = [row for row in output_rows if row["label"] == 0]
label_1 = [row for row in output_rows if row["label"] == 1]

min_len = min(len(label_0), len(label_1))

balanced_rows = label_0[:min_len] + label_1[:min_len]
random.shuffle(balanced_rows)

with open("output_with_disciplinary_category.csv", "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = [
        "sentence_1",
        "sentence_2",
        "label",
        "category",
        "title"
    ]

    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(balanced_rows)

print(f"Final balanced dataset size: {len(balanced_rows)}")
print("Saved: output_with_disciplinary_category.csv")
'''

'\nresults = []\n\nfor pair in tqdm(matched_pairs, desc="Extracting texts"):\n    cat = pair["category"]\n    title = pair["title"]\n\n    simple_text = get_page_extract(title, API_SIMPLE)\n    en_text = get_page_extract(title, API_EN)\n\n    if not is_valid_text(simple_text, min_words=100):\n        continue\n\n    if not is_valid_text(en_text, min_words=100):\n        continue\n\n    results.append({\n        "category": cat,\n        "title": title,\n        "simple_text": simple_text,\n        "en_text": en_text\n    })\n\n    time.sleep(0.1)\n\nwith open("category_title_texts_disciplinary.json", "w", encoding="utf-8") as f:\n    json.dump(results, f, ensure_ascii=False, indent=2)\n\nprint(f"Extracted valid text pairs for {len(results)} articles.")\n\n# =========================\n# 4. CREATE PAIRWISE CSV\n# =========================\n\noutput_rows = []\n\nfor entry in results:\n    simple_text = entry["simple_text"].strip()\n    en_text = entry["en_text"].strip()\n    category = entry["category"].strip()\n    title = entry["title"].strip()\n\n    label = random.randint(0, 1)\n\n    if label == 1:\n        sentence_1 = en_text\n        sentence_2 = simple_text\n    else:\n        sentence_1 = simple_text\n        sentence_2 = en_text\n\n    output_rows.append({\n        "sentence_1": sentence_1,\n        "sentence_2": sentence_2,\n        "label": label,\n        "category": category,\n        "title": title\n    })\n\n# Balance labels\nlabel_0 = [row for row in output_rows if row["label"] == 0]\nlabel_1 = [row for row in output_rows if row["label"] == 1]\n\nmin_len = min(len(label_0), len(label_1))\n\nbalanced_rows = label_0[:min_len] + label_1[:min_len]\nrandom.shuffle(balanced_rows)\n\nwith open("output_with_disciplinary_category.csv", "w", newline="", encoding="utf-8") as csvfile:\n    fieldnames = [\n        "sentence_1",\n        "sentence_2",\n        "label",\n        "category",\n        "title"\n    ]\n\n    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)\n    writer.writeheader()\n    writer.writerows(balanced_rows)\n\nprint(f"Final balanced dataset size: {len(balanced_rows)}")\nprint("Saved: output_with_disciplinary_category.csv")\n'

In [ ]:
len(matched_pairs)

10000

In [ ]:
import re

BAD_KEYWORDS = {
    "prostitution", "porn", "sexual", "abuse", "violence",
    "rape", "cannibal", "drug", "addiction", "gambling",
    "suicide", "murder", "death", "torture"
}

BAD_CATEGORIES = {
    "abuse", "addiction", "adultery", "abortion"
}

IST_PATTERN = re.compile(r"\b\w+ist(s)?\b", re.IGNORECASE)
PEOPLE_PATTERN = re.compile(r"\b(bankers?|lawyers?|politicians?)\b", re.IGNORECASE)

def is_clean(pair):
    cat = pair["category"].lower()
    title = pair["title"].lower()

    text = f"{cat} {title}"

    # 0. ❗ Keep ONLY single-word titles
    # (removes "ASEAN Declaration", "Physical abuse", etc. from your file :contentReference[oaicite:0]{index=0})
    if len(title.split()) != 1:
        return False

    # 1. Remove bad categories
    if cat in BAD_CATEGORIES:
        return False

    # 2. Remove unwanted keywords
    if any(keyword in text for keyword in BAD_KEYWORDS):
        return False

    # 3. Remove professions / groups
    if PEOPLE_PATTERN.search(text):
        return False

    # 4. Remove words ending with -ist
    if IST_PATTERN.search(text):
        return False

    return True

In [ ]:
clean_pairs = []

for pair in tqdm(matched_pairs, desc="Filtering"):
    if is_clean(pair):
        clean_pairs.append(pair)

Filtering: 100%|██████████| 10000/10000 [00:00<00:00, 446868.10it/s]

In [ ]:
import json

with open("disciplinary_categories3.json", "r") as file:
    common_cats= json.load(file)

print(len(common_cats))

267

In [ ]:
common_cats
n = [
    "Anniversaries",
    "Architects",
    "Astronauts",
    "Astronomers",
    "Beekeepers",
    "Birthdays",
    "Choreographers",
    "Dancers",
    "Engineers",
    "Firefighters",
    "Islamophobia",
    "Plumbers",
    "Statisticians",
    "Surgeons",
    "Woodworkers",
    "Zoos"
]


result = [x for x in common_cats if x not in n]

print(len(result))

257

In [ ]:
from numpy import char
import requests
import time
import json
import random
import csv
import re
from tqdm import tqdm
import pandas as pd
from google.colab import files

HEADERS = {
    "User-Agent": "MyColabBot/1.0 (inesgoddi@gmail.com)"
}

API_SIMPLE = "https://simple.wikipedia.org/w/api.php"
API_EN = "https://en.wikipedia.org/w/api.php"

# =========================
# 2. COLLECT ARTICLE TITLES
# =========================

matched_pairs = []

MAX_TOTAL_PAIRS = 10000
MAX_ARTICLES_PER_CATEGORY = 100

for cat in tqdm(result, desc="Collecting articles"):
    if len(cat.split()) >1 or any(char.isdigit() for char in cat):
        continue

    print(f"Collecting articles for category: {cat}")
    titles_simple = get_category_articles(
        cat,
        API_SIMPLE,
        limit=MAX_ARTICLES_PER_CATEGORY * 2
    )

    if not titles_simple:
        continue

    existing_in_en = filter_existing_titles_in_en(titles_simple)

    count_for_cat = 0

    for title in existing_in_en:
        matched_pairs.append({
            "category": cat,
            "title": title
        })

        count_for_cat += 1

        if count_for_cat >= MAX_ARTICLES_PER_CATEGORY:
            break

        if len(matched_pairs) >= MAX_TOTAL_PAIRS:
            break

    if len(matched_pairs) >= MAX_TOTAL_PAIRS:
        break

with open("category_title_pairs_disciplinary3.json", "w", encoding="utf-8") as f:
    json.dump(matched_pairs, f, ensure_ascii=False, indent=2)

print(f"Collected {len(matched_pairs)} category-title pairs.")
print(matched_pairs)

Collecting articles:   0%|          | 0/257 [00:00<?, ?it/s]

Collecting articles for category: Adhesives

Collecting articles:   0%|          | 1/257 [00:00<02:34,  1.66it/s]

Collecting articles for category: Aircraft

Collecting articles:   1%|          | 2/257 [00:01<03:22,  1.26it/s]

Collecting articles for category: Airships

Collecting articles:   1%|          | 3/257 [00:02<02:57,  1.43it/s]

Collecting articles for category: Algae

Collecting articles:   2%|▏         | 4/257 [00:02<02:45,  1.53it/s]

Collecting articles for category: Amphibians

Collecting articles:   2%|▏         | 5/257 [00:03<02:37,  1.60it/s]

Collecting articles for category: Angels

Collecting articles:   2%|▏         | 6/257 [00:03<02:32,  1.65it/s]

Collecting articles for category: Animals

Collecting articles:   3%|▎         | 7/257 [00:04<02:30,  1.66it/s]

Collecting articles for category: Annelids

Collecting articles:   3%|▎         | 8/257 [00:05<02:28,  1.68it/s]

Collecting articles for category: Anthropology

Collecting articles:   4%|▎         | 9/257 [00:05<02:27,  1.68it/s]

Collecting articles for category: Antisemitism

Collecting articles:   4%|▍         | 10/257 [00:06<02:52,  1.43it/s]

Collecting articles for category: Ants

Collecting articles:   4%|▍         | 11/257 [00:07<02:42,  1.52it/s]

Collecting articles for category: Aquariums

Collecting articles:   5%|▍         | 12/257 [00:07<02:36,  1.57it/s]

Collecting articles for category: Archaeology

Collecting articles:   5%|▌         | 13/257 [00:08<02:31,  1.61it/s]

Collecting articles for category: Architects

Collecting articles:   5%|▌         | 14/257 [00:08<02:27,  1.64it/s]

Collecting articles for category: Architecture

Collecting articles:   6%|▌         | 15/257 [00:09<02:24,  1.67it/s]

Collecting articles for category: Archives

Collecting articles:   6%|▌         | 16/257 [00:10<02:21,  1.70it/s]

Collecting articles for category: Archosaurs

Collecting articles:   7%|▋         | 17/257 [00:10<02:20,  1.71it/s]

Collecting articles for category: Arthropods

Collecting articles:   7%|▋         | 18/257 [00:11<02:19,  1.72it/s]

Collecting articles for category: Arts

Collecting articles:   7%|▋         | 19/257 [00:11<01:53,  2.09it/s]

Collecting articles for category: Astrology

Collecting articles:   8%|▊         | 20/257 [00:11<01:59,  1.98it/s]

Collecting articles for category: Astronauts

Collecting articles:   8%|▊         | 21/257 [00:12<02:04,  1.90it/s]

Collecting articles for category: Astronomers

Collecting articles:   9%|▊         | 22/257 [00:13<02:07,  1.84it/s]

Collecting articles for category: Astronomy

Collecting articles:   9%|▉         | 23/257 [00:14<02:34,  1.52it/s]

Collecting articles for category: Bacteria

Collecting articles:   9%|▉         | 24/257 [00:14<02:27,  1.58it/s]

Collecting articles for category: Ballistics

Collecting articles:  10%|▉         | 25/257 [00:15<02:23,  1.62it/s]

Collecting articles for category: Beekeeping

Collecting articles:  10%|█         | 26/257 [00:15<02:19,  1.65it/s]

Collecting articles for category: Biology

Collecting articles:  11%|█         | 27/257 [00:16<02:40,  1.43it/s]

Collecting articles for category: Biomes

Collecting articles:  11%|█         | 28/257 [00:17<02:31,  1.51it/s]

Collecting articles for category: Birds

Collecting articles:  11%|█▏        | 29/257 [00:18<02:48,  1.35it/s]

Collecting articles for category: Birth

Collecting articles:  12%|█▏        | 30/257 [00:18<02:36,  1.45it/s]

Collecting articles for category: Books

Collecting articles:  12%|█▏        | 31/257 [00:19<02:29,  1.52it/s]

Collecting articles for category: Botany

Collecting articles:  12%|█▏        | 32/257 [00:19<02:24,  1.56it/s]

Collecting articles for category: Botnets

Collecting articles:  13%|█▎        | 33/257 [00:20<02:18,  1.62it/s]

Collecting articles for category: Brachiopods

Collecting articles:  13%|█▎        | 34/257 [00:21<02:14,  1.65it/s]

Collecting articles for category: Business

Collecting articles:  14%|█▎        | 35/257 [00:22<02:35,  1.42it/s]

Collecting articles for category: Caecilians

Collecting articles:  14%|█▍        | 36/257 [00:22<02:26,  1.51it/s]

Collecting articles for category: Calendars

Collecting articles:  14%|█▍        | 37/257 [00:23<02:43,  1.34it/s]

Collecting articles for category: Carpenters

Collecting articles:  15%|█▍        | 38/257 [00:24<02:31,  1.45it/s]

Collecting articles for category: Centuries

Collecting articles:  15%|█▌        | 39/257 [00:24<02:24,  1.51it/s]

Collecting articles for category: Ceremonies

Collecting articles:  16%|█▌        | 40/257 [00:25<02:19,  1.56it/s]

Collecting articles for category: Charts

Collecting articles:  16%|█▌        | 41/257 [00:25<02:15,  1.59it/s]

Collecting articles for category: Chemistry

Collecting articles:  16%|█▋        | 42/257 [00:27<02:56,  1.22it/s]

Collecting articles for category: Chromosomes

Collecting articles:  17%|█▋        | 43/257 [00:27<02:40,  1.34it/s]

Collecting articles for category: Chronology

Collecting articles:  17%|█▋        | 44/257 [00:28<02:27,  1.44it/s]

Collecting articles for category: Clocks

Collecting articles:  18%|█▊        | 45/257 [00:28<02:20,  1.51it/s]

Collecting articles for category: Cloning

Collecting articles:  18%|█▊        | 46/257 [00:29<02:14,  1.57it/s]

Collecting articles for category: Cognition

Collecting articles:  18%|█▊        | 47/257 [00:30<02:10,  1.62it/s]

Collecting articles for category: Colors

Collecting articles:  19%|█▊        | 48/257 [00:30<02:07,  1.64it/s]

Collecting articles for category: Comics

Collecting articles:  19%|█▉        | 49/257 [00:31<02:04,  1.66it/s]

Collecting articles for category: Constellations

Collecting articles:  19%|█▉        | 50/257 [00:32<02:25,  1.43it/s]

Collecting articles for category: Constituencies

Collecting articles:  20%|█▉        | 51/257 [00:32<02:16,  1.50it/s]

Collecting articles for category: Construction

Collecting articles:  20%|██        | 52/257 [00:33<02:11,  1.56it/s]

Collecting articles for category: Consumer

Collecting articles:  21%|██        | 53/257 [00:33<02:06,  1.61it/s]

Collecting articles for category: Costumes

Collecting articles:  21%|██        | 54/257 [00:34<02:03,  1.64it/s]

Collecting articles for category: Creativity

Collecting articles:  21%|██▏       | 55/257 [00:35<02:00,  1.68it/s]

Collecting articles for category: Cryptozoology

Collecting articles:  22%|██▏       | 56/257 [00:35<01:58,  1.69it/s]

Collecting articles for category: Dance

Collecting articles:  22%|██▏       | 57/257 [00:36<01:57,  1.70it/s]

Collecting articles for category: Dances

Collecting articles:  23%|██▎       | 58/257 [00:36<01:57,  1.70it/s]

Collecting articles for category: Days

Collecting articles:  23%|██▎       | 59/257 [00:37<01:56,  1.70it/s]

Collecting articles for category: Decades

Collecting articles:  23%|██▎       | 60/257 [00:37<01:55,  1.71it/s]

Collecting articles for category: Demolition

Collecting articles:  24%|██▎       | 61/257 [00:38<01:54,  1.71it/s]

Collecting articles for category: Demons

Collecting articles:  24%|██▍       | 62/257 [00:39<01:53,  1.72it/s]

Collecting articles for category: Deserts

Collecting articles:  25%|██▍       | 63/257 [00:39<01:51,  1.73it/s]

Collecting articles for category: Diagrams

Collecting articles:  25%|██▍       | 64/257 [00:40<01:51,  1.73it/s]

Collecting articles for category: Diapsids

Collecting articles:  25%|██▌       | 65/257 [00:40<01:51,  1.72it/s]

Collecting articles for category: Disasters

Collecting articles:  26%|██▌       | 66/257 [00:41<01:51,  1.72it/s]

Collecting articles for category: Documents

Collecting articles:  26%|██▌       | 67/257 [00:42<01:50,  1.71it/s]

Collecting articles for category: Drama

Collecting articles:  26%|██▋       | 68/257 [00:42<01:49,  1.72it/s]

Collecting articles for category: Echinoderms

Collecting articles:  27%|██▋       | 69/257 [00:43<01:50,  1.70it/s]

Collecting articles for category: Ecology

Collecting articles:  27%|██▋       | 70/257 [00:44<02:07,  1.46it/s]

Collecting articles for category: Economics

Collecting articles:  28%|██▊       | 71/257 [00:45<02:40,  1.16it/s]

Collecting articles for category: Ecoregions

Collecting articles:  28%|██▊       | 72/257 [00:45<02:23,  1.29it/s]

Collecting articles for category: Ecosystems

Collecting articles:  28%|██▊       | 73/257 [00:46<02:11,  1.40it/s]

Collecting articles for category: Elections

Collecting articles:  29%|██▉       | 74/257 [00:47<02:03,  1.49it/s]

Collecting articles for category: Emotions

Collecting articles:  29%|██▉       | 75/257 [00:48<02:16,  1.33it/s]

Collecting articles for category: Employment

Collecting articles:  30%|██▉       | 76/257 [00:48<02:05,  1.44it/s]

Collecting articles for category: Engineering

Collecting articles:  30%|██▉       | 77/257 [00:49<02:36,  1.15it/s]

Collecting articles for category: Entomology

Collecting articles:  30%|███       | 78/257 [00:50<02:19,  1.28it/s]

Collecting articles for category: Epidemiology

Collecting articles:  31%|███       | 79/257 [00:51<02:08,  1.39it/s]

Collecting articles for category: Establishments

Collecting articles:  31%|███       | 80/257 [00:51<01:42,  1.72it/s]

Collecting articles for category: Ethnicity

Collecting articles:  32%|███▏      | 81/257 [00:51<01:41,  1.73it/s]

Collecting articles for category: Ethnocentrism

Collecting articles:  32%|███▏      | 82/257 [00:52<01:42,  1.71it/s]

Collecting articles for category: Ethnography

Collecting articles:  32%|███▏      | 83/257 [00:53<01:42,  1.70it/s]

Collecting articles for category: Ethnology

Collecting articles:  33%|███▎      | 84/257 [00:53<01:41,  1.71it/s]

Collecting articles for category: Ethology

Collecting articles:  33%|███▎      | 85/257 [00:54<01:40,  1.71it/s]

Collecting articles for category: Eukaryotes

Collecting articles:  33%|███▎      | 86/257 [00:54<01:39,  1.72it/s]

Collecting articles for category: Extinction

Collecting articles:  34%|███▍      | 87/257 [00:55<01:38,  1.73it/s]

Collecting articles for category: Extremophiles

Collecting articles:  34%|███▍      | 88/257 [00:55<01:37,  1.73it/s]

Collecting articles for category: Fashion

Collecting articles:  35%|███▍      | 89/257 [00:56<01:37,  1.72it/s]

Collecting articles for category: Fertilizers

Collecting articles:  35%|███▌      | 90/257 [00:57<01:36,  1.74it/s]

Collecting articles for category: Finance

Collecting articles:  35%|███▌      | 91/257 [00:58<01:53,  1.46it/s]

Collecting articles for category: Fire

Collecting articles:  36%|███▌      | 92/257 [00:58<01:47,  1.53it/s]

Collecting articles for category: Firefighting

Collecting articles:  36%|███▌      | 93/257 [00:59<01:43,  1.59it/s]

Collecting articles for category: Fires

Collecting articles:  37%|███▋      | 94/257 [00:59<01:39,  1.63it/s]

Collecting articles for category: Flags

Collecting articles:  37%|███▋      | 95/257 [01:00<01:37,  1.66it/s]

Collecting articles for category: Flatworms

Collecting articles:  37%|███▋      | 96/257 [01:00<01:36,  1.68it/s]

Collecting articles for category: Forestry

Collecting articles:  38%|███▊      | 97/257 [01:01<01:35,  1.68it/s]

Collecting articles for category: Forests

Collecting articles:  38%|███▊      | 98/257 [01:02<01:33,  1.70it/s]

Collecting articles for category: Frogs

Collecting articles:  39%|███▊      | 99/257 [01:02<01:33,  1.69it/s]

Collecting articles for category: Fungi

Collecting articles:  39%|███▉      | 100/257 [01:03<01:32,  1.70it/s]

Collecting articles for category: Gardening

Collecting articles:  39%|███▉      | 101/257 [01:03<01:31,  1.71it/s]

Collecting articles for category: Gardens

Collecting articles:  40%|███▉      | 102/257 [01:04<01:30,  1.72it/s]

Collecting articles for category: Gemstones

Collecting articles:  40%|████      | 103/257 [01:05<01:30,  1.71it/s]

Collecting articles for category: Genetics

Collecting articles:  40%|████      | 104/257 [01:05<01:45,  1.45it/s]

Collecting articles for category: Giftedness

Collecting articles:  41%|████      | 105/257 [01:06<01:39,  1.52it/s]

Collecting articles for category: Glaciers

Collecting articles:  41%|████      | 106/257 [01:07<01:35,  1.58it/s]

Collecting articles for category: Glass

Collecting articles:  42%|████▏     | 107/257 [01:07<01:32,  1.62it/s]

Collecting articles for category: Goods

Collecting articles:  42%|████▏     | 108/257 [01:08<01:30,  1.65it/s]

Collecting articles for category: Graphics

Collecting articles:  42%|████▏     | 109/257 [01:08<01:28,  1.66it/s]

Collecting articles for category: Grasslands

Collecting articles:  43%|████▎     | 110/257 [01:09<01:26,  1.70it/s]

Collecting articles for category: Hairstyles

Collecting articles:  43%|████▎     | 111/257 [01:09<01:25,  1.71it/s]

Collecting articles for category: Happiness

Collecting articles:  44%|████▎     | 112/257 [01:10<01:33,  1.54it/s]

Collecting articles for category: Herbicides

Collecting articles:  44%|████▍     | 113/257 [01:11<01:30,  1.59it/s]

Collecting articles for category: Hippopotamuses

Collecting articles:  44%|████▍     | 114/257 [01:11<01:27,  1.63it/s]

Collecting articles for category: Historiography

Collecting articles:  45%|████▍     | 115/257 [01:12<01:25,  1.67it/s]

Collecting articles for category: History

Collecting articles:  45%|████▌     | 116/257 [01:13<01:23,  1.69it/s]

Collecting articles for category: Humans

Collecting articles:  46%|████▌     | 117/257 [01:13<01:22,  1.70it/s]

Collecting articles for category: Hydropower

Collecting articles:  46%|████▌     | 118/257 [01:14<01:21,  1.70it/s]

Collecting articles for category: Illusions

Collecting articles:  46%|████▋     | 119/257 [01:14<01:20,  1.70it/s]

Collecting articles for category: Income

Collecting articles:  47%|████▋     | 120/257 [01:15<01:20,  1.70it/s]

Collecting articles for category: Infrastructure

Collecting articles:  47%|████▋     | 121/257 [01:15<01:19,  1.71it/s]

Collecting articles for category: Innovation

Collecting articles:  47%|████▋     | 122/257 [01:16<01:18,  1.71it/s]

Collecting articles for category: Insecticides

Collecting articles:  48%|████▊     | 123/257 [01:17<01:17,  1.72it/s]

Collecting articles for category: Insects

Collecting articles:  48%|████▊     | 124/257 [01:18<01:31,  1.46it/s]

Collecting articles for category: Intelligence

Collecting articles:  49%|████▊     | 125/257 [01:18<01:26,  1.52it/s]

Collecting articles for category: Invertebrates

Collecting articles:  49%|████▉     | 126/257 [01:19<01:22,  1.58it/s]

Collecting articles for category: Journalism

Collecting articles:  49%|████▉     | 127/257 [01:19<01:20,  1.62it/s]

Collecting articles for category: Labor

Collecting articles:  50%|████▉     | 128/257 [01:20<01:18,  1.64it/s]

Collecting articles for category: Learning

Collecting articles:  50%|█████     | 129/257 [01:20<01:16,  1.68it/s]

Collecting articles for category: Light

Collecting articles:  51%|█████     | 130/257 [01:21<01:15,  1.69it/s]

Collecting articles for category: Lighthouses

Collecting articles:  51%|█████     | 131/257 [01:22<01:14,  1.70it/s]

Collecting articles for category: Lighting

Collecting articles:  51%|█████▏    | 132/257 [01:22<01:13,  1.69it/s]

Collecting articles for category: Linguistics

Collecting articles:  52%|█████▏    | 133/257 [01:23<01:26,  1.44it/s]

Collecting articles for category: Literature

Collecting articles:  52%|█████▏    | 134/257 [01:24<01:21,  1.52it/s]

Collecting articles for category: Logic

Collecting articles:  53%|█████▎    | 135/257 [01:25<01:29,  1.36it/s]

Collecting articles for category: Logistics

Collecting articles:  53%|█████▎    | 136/257 [01:25<01:23,  1.45it/s]

Collecting articles for category: Love

Collecting articles:  53%|█████▎    | 137/257 [01:26<01:18,  1.53it/s]

Collecting articles for category: Luck

Collecting articles:  54%|█████▎    | 138/257 [01:26<01:15,  1.58it/s]

Collecting articles for category: Machines

Collecting articles:  54%|█████▍    | 139/257 [01:27<01:24,  1.39it/s]

Collecting articles for category: Mammals

Collecting articles:  54%|█████▍    | 140/257 [01:28<01:19,  1.48it/s]

Collecting articles for category: Management

Collecting articles:  55%|█████▍    | 141/257 [01:28<01:15,  1.53it/s]

Collecting articles for category: Manga

Collecting articles:  55%|█████▌    | 142/257 [01:29<01:23,  1.37it/s]

Collecting articles for category: Manufacturing

Collecting articles:  56%|█████▌    | 143/257 [01:30<01:18,  1.46it/s]

Collecting articles for category: Manuscripts

Collecting articles:  56%|█████▌    | 144/257 [01:31<01:13,  1.53it/s]

Collecting articles for category: Marxism

Collecting articles:  56%|█████▋    | 145/257 [01:31<01:10,  1.60it/s]

Collecting articles for category: Mascots

Collecting articles:  57%|█████▋    | 146/257 [01:32<01:08,  1.63it/s]

Collecting articles for category: Materials

Collecting articles:  57%|█████▋    | 147/257 [01:33<01:13,  1.50it/s]

Collecting articles for category: Mathematics

Collecting articles:  58%|█████▊    | 148/257 [01:34<01:43,  1.05it/s]

Collecting articles for category: Mechanics

Collecting articles:  58%|█████▊    | 149/257 [01:35<01:42,  1.06it/s]

Collecting articles for category: Medicine

Collecting articles:  58%|█████▊    | 150/257 [01:37<02:03,  1.16s/it]

Collecting articles for category: Mesonychids

Collecting articles:  59%|█████▉    | 151/257 [01:37<01:44,  1.02it/s]

Collecting articles for category: Metalworking

Collecting articles:  59%|█████▉    | 152/257 [01:38<01:31,  1.15it/s]

Collecting articles for category: Microbiology

Collecting articles:  60%|█████▉    | 153/257 [01:38<01:21,  1.27it/s]

Collecting articles for category: Migraine

Collecting articles:  60%|█████▉    | 154/257 [01:39<01:14,  1.38it/s]

Collecting articles for category: Millennia

Collecting articles:  60%|██████    | 155/257 [01:40<01:09,  1.48it/s]

Collecting articles for category: Modernism

Collecting articles:  61%|██████    | 156/257 [01:41<01:16,  1.32it/s]

Collecting articles for category: Modernity

Collecting articles:  61%|██████    | 157/257 [01:41<01:10,  1.43it/s]

Collecting articles for category: Molluscs

Collecting articles:  61%|██████▏   | 158/257 [01:42<01:05,  1.51it/s]

Collecting articles for category: Money

Collecting articles:  62%|██████▏   | 159/257 [01:42<01:02,  1.56it/s]

Collecting articles for category: Months

Collecting articles:  62%|██████▏   | 160/257 [01:43<01:00,  1.61it/s]

Collecting articles for category: Mosaics

Collecting articles:  63%|██████▎   | 161/257 [01:43<00:58,  1.64it/s]

Collecting articles for category: Museums

Collecting articles:  63%|██████▎   | 162/257 [01:44<01:02,  1.52it/s]

Collecting articles for category: Music

Collecting articles:  63%|██████▎   | 163/257 [01:45<00:59,  1.57it/s]

Collecting articles for category: Narcissism

Collecting articles:  64%|██████▍   | 164/257 [01:45<00:57,  1.61it/s]

Collecting articles for category: Nematodes

Collecting articles:  64%|██████▍   | 165/257 [01:46<00:55,  1.65it/s]

Collecting articles for category: Neuropsychology

Collecting articles:  65%|██████▍   | 166/257 [01:47<00:54,  1.67it/s]

Collecting articles for category: Neuroscience

Collecting articles:  65%|██████▍   | 167/257 [01:47<00:53,  1.68it/s]

Collecting articles for category: Newts

Collecting articles:  65%|██████▌   | 168/257 [01:48<00:52,  1.70it/s]

Collecting articles for category: Nucleotides

Collecting articles:  66%|██████▌   | 169/257 [01:48<00:51,  1.70it/s]

Collecting articles for category: Observances

Collecting articles:  66%|██████▌   | 170/257 [01:49<00:50,  1.71it/s]

Collecting articles for category: Observation

Collecting articles:  67%|██████▋   | 171/257 [01:49<00:49,  1.72it/s]

Collecting articles for category: Occupations

Collecting articles:  67%|██████▋   | 172/257 [01:50<00:57,  1.47it/s]

Collecting articles for category: Opera

Collecting articles:  67%|██████▋   | 173/257 [01:51<00:55,  1.53it/s]

Collecting articles for category: Operas

Collecting articles:  68%|██████▊   | 174/257 [01:52<00:52,  1.58it/s]

Collecting articles for category: Optoelectronics

Collecting articles:  68%|██████▊   | 175/257 [01:52<00:50,  1.62it/s]

Collecting articles for category: Organisms

Collecting articles:  68%|██████▊   | 176/257 [01:53<00:48,  1.66it/s]

Collecting articles for category: Oscillation

Collecting articles:  69%|██████▉   | 177/257 [01:53<00:47,  1.69it/s]

Collecting articles for category: Pain

Collecting articles:  69%|██████▉   | 178/257 [01:54<00:46,  1.69it/s]

Collecting articles for category: Paints

Collecting articles:  70%|██████▉   | 179/257 [01:54<00:46,  1.69it/s]

Collecting articles for category: Pamphlets

Collecting articles:  70%|███████   | 180/257 [01:55<00:45,  1.70it/s]

Collecting articles for category: Parades

Collecting articles:  70%|███████   | 181/257 [01:56<00:44,  1.71it/s]

Collecting articles for category: Parasites

Collecting articles:  71%|███████   | 182/257 [01:56<00:44,  1.69it/s]

Collecting articles for category: Pendulums

Collecting articles:  71%|███████   | 183/257 [01:57<00:43,  1.71it/s]

Collecting articles for category: Perception

Collecting articles:  72%|███████▏  | 184/257 [01:57<00:42,  1.72it/s]

Collecting articles for category: Perfumery

Collecting articles:  72%|███████▏  | 185/257 [01:58<00:42,  1.71it/s]

Collecting articles for category: Personality

Collecting articles:  72%|███████▏  | 186/257 [01:59<00:41,  1.72it/s]

Collecting articles for category: Pesticides

Collecting articles:  73%|███████▎  | 187/257 [01:59<00:40,  1.71it/s]

Collecting articles for category: Pharmacology

Collecting articles:  73%|███████▎  | 188/257 [02:00<00:40,  1.72it/s]

Collecting articles for category: Phenomena

Collecting articles:  74%|███████▎  | 189/257 [02:00<00:39,  1.71it/s]

Collecting articles for category: Philosophy

Collecting articles:  74%|███████▍  | 190/257 [02:02<00:53,  1.25it/s]

Collecting articles for category: Phobias

Collecting articles:  74%|███████▍  | 191/257 [02:02<00:48,  1.36it/s]

Collecting articles for category: Photovoltaics

Collecting articles:  75%|███████▍  | 192/257 [02:03<00:44,  1.45it/s]

Collecting articles for category: Physics

Collecting articles:  75%|███████▌  | 193/257 [02:05<01:09,  1.08s/it]

Collecting articles for category: Plays

Collecting articles:  75%|███████▌  | 194/257 [02:05<00:58,  1.07it/s]

Collecting articles for category: Poisons

Collecting articles:  76%|███████▌  | 195/257 [02:06<00:51,  1.21it/s]

Collecting articles for category: Pottery

Collecting articles:  76%|███████▋  | 196/257 [02:06<00:46,  1.32it/s]

Collecting articles for category: Prevention

Collecting articles:  77%|███████▋  | 197/257 [02:07<00:42,  1.43it/s]

Collecting articles for category: Profanity

Collecting articles:  77%|███████▋  | 198/257 [02:08<00:38,  1.52it/s]

Collecting articles for category: Prokaryotes

Collecting articles:  77%|███████▋  | 199/257 [02:08<00:36,  1.58it/s]

Collecting articles for category: Psychology

Collecting articles:  78%|███████▊  | 200/257 [02:10<00:52,  1.08it/s]

Collecting articles for category: Publications

Collecting articles:  78%|███████▊  | 201/257 [02:10<00:45,  1.22it/s]

Collecting articles for category: Punctuation

Collecting articles:  79%|███████▊  | 202/257 [02:11<00:41,  1.33it/s]

Collecting articles for category: Rainforests

Collecting articles:  79%|███████▉  | 203/257 [02:12<00:37,  1.44it/s]

Collecting articles for category: Rationalism

Collecting articles:  79%|███████▉  | 204/257 [02:12<00:34,  1.52it/s]

Collecting articles for category: Reasoning

Collecting articles:  80%|███████▉  | 205/257 [02:13<00:33,  1.58it/s]

Collecting articles for category: Referendums

Collecting articles:  80%|████████  | 206/257 [02:13<00:31,  1.62it/s]

Collecting articles for category: Reptiles

Collecting articles:  81%|████████  | 207/257 [02:14<00:30,  1.65it/s]

Collecting articles for category: Rhetoric

Collecting articles:  81%|████████  | 208/257 [02:14<00:29,  1.68it/s]

Collecting articles for category: Robots

Collecting articles:  81%|████████▏ | 209/257 [02:15<00:28,  1.69it/s]

Collecting articles for category: Salamanders

Collecting articles:  82%|████████▏ | 210/257 [02:16<00:27,  1.70it/s]

Collecting articles for category: Salamandridae

Collecting articles:  82%|████████▏ | 211/257 [02:16<00:26,  1.71it/s]

Collecting articles for category: Satellites

Collecting articles:  82%|████████▏ | 212/257 [02:17<00:31,  1.43it/s]

Collecting articles for category: Scorpius

Collecting articles:  83%|████████▎ | 213/257 [02:18<00:29,  1.51it/s]

Collecting articles for category: Seasons

Collecting articles:  83%|████████▎ | 214/257 [02:18<00:27,  1.57it/s]

Collecting articles for category: Semiconductors

Collecting articles:  84%|████████▎ | 215/257 [02:19<00:26,  1.60it/s]

Collecting articles for category: Smartwatches

Collecting articles:  84%|████████▍ | 216/257 [02:19<00:24,  1.65it/s]

Collecting articles for category: Snow

Collecting articles:  84%|████████▍ | 217/257 [02:20<00:24,  1.66it/s]

Collecting articles for category: Sociology

Collecting articles:  85%|████████▍ | 218/257 [02:21<00:31,  1.25it/s]

Collecting articles for category: Software

Collecting articles:  85%|████████▌ | 219/257 [02:23<00:39,  1.05s/it]

Collecting articles for category: Spacecraft

Collecting articles:  86%|████████▌ | 220/257 [02:23<00:33,  1.10it/s]

Collecting articles for category: Spaceflight

Collecting articles:  86%|████████▌ | 221/257 [02:24<00:29,  1.23it/s]

Collecting articles for category: Sponges

Collecting articles:  86%|████████▋ | 222/257 [02:25<00:26,  1.34it/s]

Collecting articles for category: Statisticians

Collecting articles:  87%|████████▋ | 223/257 [02:25<00:23,  1.44it/s]

Collecting articles for category: Statistics

Collecting articles:  87%|████████▋ | 224/257 [02:26<00:25,  1.30it/s]

Collecting articles for category: Submarines

Collecting articles:  88%|████████▊ | 225/257 [02:27<00:22,  1.41it/s]

Collecting articles for category: Surgeons

Collecting articles:  88%|████████▊ | 226/257 [02:27<00:20,  1.49it/s]

Collecting articles for category: Surgery

Collecting articles:  88%|████████▊ | 227/257 [02:28<00:22,  1.34it/s]

Collecting articles for category: Surrealism

Collecting articles:  89%|████████▊ | 228/257 [02:29<00:20,  1.44it/s]

Collecting articles for category: Symbols

Collecting articles:  89%|████████▉ | 229/257 [02:30<00:21,  1.32it/s]

Collecting articles for category: Television

Collecting articles:  89%|████████▉ | 230/257 [02:31<00:21,  1.23it/s]

Collecting articles for category: Tetrapods

Collecting articles:  90%|████████▉ | 231/257 [02:31<00:19,  1.35it/s]

Collecting articles for category: Theatre

Collecting articles:  90%|█████████ | 232/257 [02:32<00:17,  1.44it/s]

Collecting articles for category: Theatres

Collecting articles:  91%|█████████ | 233/257 [02:32<00:15,  1.51it/s]

Collecting articles for category: Theism

Collecting articles:  91%|█████████ | 234/257 [02:33<00:14,  1.57it/s]

Collecting articles for category: Theology

Collecting articles:  91%|█████████▏| 235/257 [02:34<00:15,  1.38it/s]

Collecting articles for category: Toads

Collecting articles:  92%|█████████▏| 236/257 [02:35<00:16,  1.27it/s]

Collecting articles for category: Tourism

Collecting articles:  92%|█████████▏| 237/257 [02:35<00:14,  1.38it/s]

Collecting articles for category: Trade

Collecting articles:  93%|█████████▎| 238/257 [02:36<00:12,  1.46it/s]

Collecting articles for category: Training

Collecting articles:  93%|█████████▎| 239/257 [02:37<00:11,  1.53it/s]

Collecting articles for category: Treaties

Collecting articles:  93%|█████████▎| 240/257 [02:37<00:10,  1.59it/s]

Collecting articles for category: Tropes

Collecting articles:  94%|█████████▍| 241/257 [02:38<00:09,  1.63it/s]

Collecting articles for category: Turtles

Collecting articles:  94%|█████████▍| 242/257 [02:38<00:09,  1.65it/s]

Collecting articles for category: Ungulates

Collecting articles:  95%|█████████▍| 243/257 [02:39<00:08,  1.68it/s]

Collecting articles for category: Vaccines

Collecting articles:  95%|█████████▍| 244/257 [02:39<00:07,  1.69it/s]

Collecting articles for category: Vehicles

Collecting articles:  95%|█████████▌| 245/257 [02:40<00:07,  1.68it/s]

Collecting articles for category: Vultures

Collecting articles:  96%|█████████▌| 246/257 [02:41<00:06,  1.70it/s]

Collecting articles for category: Watches

Collecting articles:  96%|█████████▌| 247/257 [02:41<00:04,  2.07it/s]

Collecting articles for category: Water

Collecting articles:  96%|█████████▋| 248/257 [02:42<00:05,  1.61it/s]

Collecting articles for category: Waves

Collecting articles:  97%|█████████▋| 249/257 [02:42<00:04,  1.64it/s]

Collecting articles for category: Wetlands

Collecting articles:  97%|█████████▋| 250/257 [02:43<00:04,  1.66it/s]

Collecting articles for category: Wolves

Collecting articles:  98%|█████████▊| 251/257 [02:44<00:03,  1.67it/s]

Collecting articles for category: Woodworkers

Collecting articles:  98%|█████████▊| 252/257 [02:44<00:02,  1.69it/s]

Collecting articles for category: Woodworking

Collecting articles:  98%|█████████▊| 253/257 [02:45<00:02,  1.69it/s]

Collecting articles for category: Xenacoelomorpha

Collecting articles:  99%|█████████▉| 254/257 [02:45<00:01,  1.71it/s]

Collecting articles for category: Xenophobia

Collecting articles:  99%|█████████▉| 255/257 [02:46<00:01,  1.72it/s]

Collecting articles for category: Years

Collecting articles: 100%|█████████▉| 256/257 [02:46<00:00,  1.73it/s]

Collecting articles for category: Zoology

Collecting articles: 100%|██████████| 257/257 [02:47<00:00,  1.53it/s]

Collected 6342 category-title pairs.

In [ ]:
# =========================
# 3. EXTRACT SIMPLE + EN TEXTS
# =========================

results = []

for pair in tqdm(matched_pairs, desc="Extracting texts"):
    cat = pair["category"]
    title = pair["title"]

    simple_text = get_page_extract(title, API_SIMPLE)
    en_text = get_page_extract(title, API_EN)


    results.append({
        "category": cat,
        "title": title,
        "simple_text": simple_text,
        "en_text": en_text
    })

    time.sleep(0.1)

with open("category_title_texts_disciplinary3.json", "w", encoding="utf-8") as f:
    json.dump(results, f, ensure_ascii=False, indent=2)

print(f"Extracted valid text pairs for {len(results)} articles.")

# =========================
# 4. CREATE PAIRWISE CSV
# =========================

output_rows = []

for entry in results:
    if entry is None or entry.get("simple_text") is None or entry.get("en_text") is None:
      continue
    simple_text = entry["simple_text"].strip()
    en_text = entry["en_text"].strip()
    category = entry["category"].strip()
    title = entry["title"].strip()

    label = random.randint(0, 1)

    if label == 1:
        sentence_1 = en_text
        sentence_2 = simple_text
    else:
        sentence_1 = simple_text
        sentence_2 = en_text

    output_rows.append({
        "sentence_1": sentence_1,
        "sentence_2": sentence_2,
        "label": label,
        "category": category,
        "title": title
    })

# Balance labels
label_0 = [row for row in output_rows if row["label"] == 0]
label_1 = [row for row in output_rows if row["label"] == 1]

min_len = min(len(label_0), len(label_1))

balanced_rows = label_0[:min_len] + label_1[:min_len]
random.shuffle(balanced_rows)

with open("output_with_disciplinary_category.csv", "w", newline="", encoding="utf-8") as csvfile:
    fieldnames = [
        "sentence_1",
        "sentence_2",
        "label",
        "category",
        "title"
    ]

    writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(balanced_rows)

print(f"Final balanced dataset size: {len(balanced_rows)}")
print("Saved: output_with_disciplinary_category.csv")

Extracting texts: 100%|██████████| 6342/6342 [1:15:15<00:00,  1.40it/s]

Extracted valid text pairs for 6342 articles.
Final balanced dataset size: 5808
Saved: output_with_disciplinary_category.csv

In [ ]:
count = 0
for i, entry in enumerate(results):
    if entry is None or entry.get("simple_text") is None:
        count += 1
print(count)

483

In [ ]:
import pandas as pd

df = pd.read_csv("output_with_disciplinary_category.csv")
print(len(df))
print(df.head())

5808
                                          sentence_1  \
0  Archosauromorpha is a clade of diapsid reptile...
1  Detective Conan (名探偵コナン, Meitantei Konan), als...
2  Consonant mutation is change in a consonant in...
3  Xenophobia (from Ancient Greek  ξένος (xénos) ...
4  The meat ant (Iridomyrmex purpureus), also cal...

                                          sentence_2  label     category  \
0  Archosauromorpha (Greek for "ruling lizard for...      0     Reptiles
1  Case Closed, also officially known as Detectiv...      0        Manga
2  Consonant mutation is a feature in languages w...      1  Linguistics
3  Xenophobia is the fear or dislike of strangers...      1   Xenophobia
4  The meat ant (Iridomyrmex purpureus), also kno...      0         Ants

                title
0    Archosauromorpha
1         Case Closed
2  Consonant mutation
3          Xenophobia
4            Meat ant

In [ ]:
df

,sentence_1,sentence_2,label,category,title
0,Archosauromorpha is a clade of diapsid reptile...,"Archosauromorpha (Greek for ""ruling lizard for...",0,Reptiles,Archosauromorpha
1,"Detective Conan (名探偵コナン, Meitantei Konan), als...","Case Closed, also officially known as Detectiv...",0,Manga,Case Closed
2,Consonant mutation is change in a consonant in...,Consonant mutation is a feature in languages w...,1,Linguistics,Consonant mutation
3,Xenophobia (from Ancient Greek ξένος (xénos) ...,Xenophobia is the fear or dislike of strangers...,1,Xenophobia,Xenophobia
4,"The meat ant (Iridomyrmex purpureus), also cal...","The meat ant (Iridomyrmex purpureus), also kno...",0,Ants,Meat ant
...,...,...,...,...,...
5803,The mole (symbol: mol) is the SI unit used to ...,The mole (symbol mol) is a unit of measurement...,0,Chemistry,Mole (unit)
5804,A siphon is a long tube-like structure that is...,A siphon is an anatomical structure which is p...,0,Molluscs,Siphon (mollusc)
5805,Shogun Warriors may refer to:\n\nShogun Warrio...,Shogun Warriors was a line of robot toyline re...,1,Robots,Shogun Warriors
5806,Discovery is the act of detecting something ne...,Discovery is the act of detecting something ne...,1,Cognition,Discovery (observation)
5807,"MBM is shortened from MultiBitMap which, as th...",MBM (an abbreviation of Multibitmap) is a file...,1,Graphics,MBM (file format)

In [ ]:
pip install pylatexenc

Requirement already satisfied: pylatexenc in /usr/local/lib/python3.12/dist-packages (2.10)

In [ ]:
# ---------------------------
# Install ftfy if needed
# ---------------------------
try:
    import ftfy
except ImportError:
    !pip install ftfy
    import ftfy

# ---------------------------
# Imports
# ---------------------------
import pandas as pd
from bs4 import BeautifulSoup
import re
from google.colab import drive
from pylatexenc.latex2text import LatexNodes2Text
'''
# ---------------------------
# Mount Drive
# ---------------------------
drive.mount('/content/drive')

# ---------------------------
# 1️⃣ Load CSV safely
# ---------------------------
file_path = '/content/drive/MyDrive/output_with_disciplinary_category.csv'
'''
import pandas as pd
import csv

file_path = "output_with_disciplinary_category.csv"

try:
    df1 = pd.read_csv(file_path, encoding="utf-8")
except UnicodeDecodeError:
    df1 = pd.read_csv(file_path, encoding="latin1")

print("CSV loaded. Rows:", len(df1))

# ---------------------------
# 2️⃣ Preserve original content
# ---------------------------
df1['sentence_1_orig'] = df1['sentence_1']
df1['sentence_2_orig'] = df1['sentence_2']

# ---------------------------
# 3️⃣ Cleaning function with reason tracking
# ---------------------------
def clean_text_with_reason(text):
    if pd.isna(text):
        return "", "original_nan"

    original = str(text)

    # Fix encoding
    cleaned = ftfy.fix_text(original)

    # Remove HTML
    cleaned = BeautifulSoup(cleaned, "html.parser").get_text()

    converter = LatexNodes2Text(strict_latex=False)
    cleaned = converter.latex_to_text(cleaned)

    # Step 2: Remove leftover {\displaystyle ...} blocks
    cleaned = re.sub(r'\{\\displaystyle\s+.*?\}', '', cleaned, flags=re.DOTALL)

    # Step 3: Remove zero-width and formatting artifacts
    cleaned = cleaned.replace('\u2061', '')  # invisible function-application char

    # Remove wiki headers
    cleaned = re.sub(r'==.*?==', '', cleaned)

    # Normalize whitespace
    cleaned = re.sub(r'\s+', ' ', cleaned).strip()

    # Content destroyed by cleaning
    if original.strip() != "" and cleaned == "":
        return "", "content_removed_by_cleaning"

    return cleaned, ""

# ---------------------------
# 4️⃣ Apply cleaning with reasons
# ---------------------------
df1[['sentence_1_clean', 'sentence_1_reason']] = (
    df1['sentence_1'].apply(lambda x: pd.Series(clean_text_with_reason(x)))
)

df1[['sentence_2_clean', 'sentence_2_reason']] = (
    df1['sentence_2'].apply(lambda x: pd.Series(clean_text_with_reason(x)))
)

# ---------------------------
# 5️⃣ Convert destroyed content to NaN
# ---------------------------
df1.loc[df1['sentence_1_reason'] == "content_removed_by_cleaning", 'sentence_1_clean'] = pd.NA
df1.loc[df1['sentence_2_reason'] == "content_removed_by_cleaning", 'sentence_2_clean'] = pd.NA

# ---------------------------
# 6️⃣ Report destroyed rows
# ---------------------------
for col in ['sentence_1', 'sentence_2']:
    reason_col = f"{col}_reason"
    clean_col = f"{col}_clean"
    orig_col = f"{col}_orig"

    count = (df1[reason_col] == "content_removed_by_cleaning").sum()

    if count > 0:
        print(f"\n⚠️ {count} rows in {col} became NaN due to cleaning")
        print(df1.loc[df1[reason_col] == "content_removed_by_cleaning",
                     [orig_col, clean_col]].head())
    else:
        print(f"✅ No content destroyed in {col}")

# ---------------------------
# 7️⃣ Optional: check leftover markup
# ---------------------------
html_like = re.compile(r'<[^>]+>|==.*==|\$.*\$')

suspicious_rows = df1[
    df1['sentence_1_clean'].astype(str).str.contains(html_like, na=False) |
    df1['sentence_2_clean'].astype(str).str.contains(html_like, na=False)
]

if not suspicious_rows.empty:
    print(f"\n⚠️ Suspicious markup remains in {len(suspicious_rows)} rows")
else:
    print("\n✅ No leftover markup detected")

# ---------------------------
# 8️⃣ Save cleaned dataframe
# ---------------------------

# Drop rows where sentence_1_clean or sentence_2_clean is NaN
df1 = df1.dropna(subset=['sentence_1_clean', 'sentence_2_clean'])

# Optional: reset the index
df1 = df1.reset_index(drop=True)

print(f"✅ Remaining rows: {len(df1)}")

df1['sentence_1'] = df1['sentence_1_clean']
df1['sentence_2'] = df1['sentence_2_clean']
df1 = df1[['sentence_1', 'sentence_2', 'label','category','title']]

output_path = 'output_cleaned_title.csv'
df1.to_csv(output_path, index=False)
print(f"\n💾 Cleaned CSV saved to: {output_path}")

WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']

CSV loaded. Rows: 5808

Le flux de sortie a été tronqué et ne contient que les 5000 dernières lignes.
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']
WARNING:pylatexenc.latex2text:LatexNodes2Text(): Unknown flag(s) encountered: ['strict_latex']

✅ No content destroyed in sentence_1
✅ No content destroyed in sentence_2

⚠️ Suspicious markup remains in 112 rows
✅ Remaining rows: 5808

💾 Cleaned CSV saved to: output_cleaned_title.csv

In [ ]:
df1

,sentence_1,sentence_2,label,category
0,Archosauromorpha is a clade of diapsid reptile...,"Archosauromorpha (Greek for ""ruling lizard for...",0,Reptiles
1,"Detective Conan (名探偵コナン, Meitantei Konan), als...","Case Closed, also officially known as Detectiv...",0,Manga
2,Consonant mutation is change in a consonant in...,Consonant mutation is a feature in languages w...,1,Linguistics
3,Xenophobia (from Ancient Greek ξένος (xénos) '...,Xenophobia is the fear or dislike of strangers...,1,Xenophobia
4,"The meat ant (Iridomyrmex purpureus), also cal...","The meat ant (Iridomyrmex purpureus), also kno...",0,Ants
...,...,...,...,...
5803,The mole (symbol: mol) is the SI unit used to ...,The mole (symbol mol) is a unit of measurement...,0,Chemistry
5804,A siphon is a long tube-like structure that is...,A siphon is an anatomical structure which is p...,0,Molluscs
5805,Shogun Warriors may refer to: Shogun Warriors ...,Shogun Warriors was a line of robot toyline re...,1,Robots
5806,Discovery is the act of detecting something ne...,Discovery is the act of detecting something ne...,1,Cognition
5807,"MBM is shortened from MultiBitMap which, as th...",MBM (an abbreviation of Multibitmap) is a file...,1,Graphics

In [ ]:
from google.colab import files
files.download('output_cleaned_title.csv')

In [ ]:
import pandas as pd

df = pd.read_csv("output_cleaned_title.csv")
print(len(df))
print(df.head())

5808
                                          sentence_1  \
0  Archosauromorpha is a clade of diapsid reptile...
1  Detective Conan (名探偵コナン, Meitantei Konan), als...
2  Consonant mutation is change in a consonant in...
3  Xenophobia (from Ancient Greek ξένος (xénos) '...
4  The meat ant (Iridomyrmex purpureus), also cal...

                                          sentence_2  label     category  \
0  Archosauromorpha (Greek for "ruling lizard for...      0     Reptiles
1  Case Closed, also officially known as Detectiv...      0        Manga
2  Consonant mutation is a feature in languages w...      1  Linguistics
3  Xenophobia is the fear or dislike of strangers...      1   Xenophobia
4  The meat ant (Iridomyrmex purpureus), also kno...      0         Ants

                title
0    Archosauromorpha
1         Case Closed
2  Consonant mutation
3          Xenophobia
4            Meat ant